govuk-one-login/ipv-cri-kbv-api

.github/workflows/deploy.yml
template.yaml

Update SSM parameter name to bring into line with naming convention updates.
The parameter name changed due to conventions introduced with the new AWS account.
- [KBV-177](https://govukverify.atlassian.net/browse/KBV-177)
None

[KBV-177] correct deployment options and parameter path

---

.github/workflows/deploy.yml

Update template path for deploy.
The SAM template path was incorrect for the deployment.
- [KBV-177](https://govukverify.atlassian.net/browse/KBV-177)
None

[KBV-177] Correct template path

---

build.gradle
lambdas/answer/build.gradle
lambdas/build.gradle
lambdas/question/build.gradle
lambdas/session/build.gradle
lib/build.gradle

Defined all dependencies in root build.gradle file
Other `build.gradle` to use the configuration section of the root `build.gradle` for dependencies
Centralising dependencies allow changing it in just one location
- [KBV-179](https://govukverify.atlassian.net/browse/KBV-179)

KBV-179:  improvement on seperate gradle build

---

build.gradle
lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java
lambdas/question/src/main/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandler.java
lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/NextTransId.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionState.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionsResponse.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/persistence/item/KBVSessionItem.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/ExperianService.java
lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionStateTest.java
lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/ExperianServiceTest.java

Changes have been made to the current flow for question/answer flow for the frontend to reflect the same sequence as seen on https://github.com/alphagov/digital-identity-architecture/blob/cri-kbv-experian-comms/rfc/2022.1-kbv-sequence-diagram.md
Refactored the code to move logic into separate methods and added unit tests

Changes to fix the question response flow

---

.github/workflows/deploy.yml
build.gradle
lambdas/answer/build.gradle
lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java
lambdas/question/build.gradle
lambdas/question/src/main/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandler.java
lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java
lambdas/session/build.gradle
lambdas/session/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/SessionHandler.java
lambdas/session/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/SessionHandlerTest.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/ExperianService.java

Added AWS powertools to the lambda functions, refactored handlers and tests, and restructured the gradle files

BAU: Added AWS powertools, refactored handlers and restructured the gradle files within lambda folders

---

.github/workflows/deploy.yml

Needed to correct the paths for the template.yaml file in the deploy scripts for github actions

BAU: corrected the template path in deploy script for .github action

---

deploy/api.yaml
deploy/template.yaml

We haven't wired up the api.yaml file this PR does this

BAU: Use open api definition

---

.github/workflows/pre-merge-integration-test.yml
infrastructure/lambda/api.yaml
infrastructure/lambda/template.yaml

merge workflow and restructure changes
merge workflow and restructure changes to bring up to date
- [KBV-380](https://govukverify.atlassian.net/browse/KBV-380)
None

[KBV-380] merge workflow and restructure changes

---

README.md
infrastructure/lambda/template.yaml

Added VPC configuration to the lambda template and updated the readme to correct the secrets
So that the safe listed EIP's can be used by the functions when making requests to Experian
- [KBV-396](https://govukverify.atlassian.net/browse/KBV-396)
The README has been updated to correctly reflect  the secrets used by the different workflows.

[KBV-396] add VPC configuration to template and update README

---

infrastructure/lambda/template.yaml

Use API keys from core-infrastructure stack.
Use keys that are less ephemeral.
- [KBV-401](https://govukverify.atlassian.net/browse/KBV-401)

KBV-401 Import API keys from core-infra stack

---

infrastructure/lambda/api.yaml
infrastructure/lambda/template.yaml

Added the (common) token lambda function to the AWS stack
- [KBV-136](https://govukverify.atlassian.net/browse/KBV-136)

KBV-136 - Add (common) token endpoint to infra

---

infrastructure/lambda/template.yaml
lambdas/answer/build.gradle
lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java
lambdas/question/build.gradle
lambdas/question/src/main/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandler.java
lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/KBVStorageService.java

Added changes to integrate audit events CRI's in all handlers
- [KBV-432](https://govukverify.atlassian.net/browse/KBV-432)

Integrate audit event feature for KBV CRI

---

infrastructure/lambda/api.yaml
infrastructure/lambda/template.yaml
settings.gradle

Added a new lambda function to retrieve the authorisation code value from the session table
Verb: GET
Path: /authorization  ( this matches the passport endpoint )
Request header: session-id
Request query-string parameters:
client_id, response_type=code, redirect_uri, scope, state
Added new project in `common-lambdas`
- [KBV-480](https://govukverify.atlassian.net/browse/KBV-480)

Create authorization endpoint

---

infrastructure/lambda/template.yaml

- [KBV-XXXX](https://govukverify.atlassian.net/browse/KBV-XXX)

BAU: Update KBV secret manager IAM issue

---

lambdas/question/src/main/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandler.java

We already newed up the configurationService, we don't have to do
it again. Extract logic to deal with creating instance of KBVItem with sessionId set
into it's own method

BAU: Remove unneccessary configuration instance

---

infrastructure/lambda/template.yaml
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/KeyStoreService.java

* Refer to the correct KBV API stack name in our IAM policy
* Refer to the correct KBV API stack name in our `KeyStoreService` class
We must refactor this to refer to the stack name set as an env var.
- [KBV-433](https://govukverify.atlassian.net/browse/KBV-433)

KBV-433 Refer to the correct KBV API stack name

---

lambdas/question/src/main/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandler.java

Bugfix to prepare an intitial question state

KBV-507 Bugfix to prepare an intitial question state

---

lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
lambdas/question/src/main/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandler.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGateway.java

- [KBV-XXXX](https://govukverify.atlassian.net/browse/KBV-XXX)

Added new console log messages for debug purposes

---

lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandler.java
lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandlerTest.java
lambdas/question/src/main/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandler.java
lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java

Emit metrics from our KBV lambdas so we can observe health.
Added metrics and updated metric values.

KBV-510Add metrics indicating success or failure to our KBV lambdas

---

lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java
lambdas/question/src/main/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandler.java
lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/config/ConfigurationConstants.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGateway.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/security/Base64TokenCacheLoader.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/security/KBVClientFactory.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/security/SoapToken.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/AWSSecretsRetriever.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/KBVService.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/KBVServiceFactory.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/KBVSystemProperty.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/KeyStoreService.java
lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/KBVServiceTest.java

Reverts alphagov/di-ipv-cri-kbv-api#67

Revert "Revert "KBV-515: Get Experian endpoints from secrets""

---

lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
lambdas/question/src/main/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandler.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGateway.java

Code cleanup activity be removing the logging statements and the variables from constructor

Remove logging and cleanup variables in audit service constructor

---

lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
lambdas/answer/src/main/resources/log4j2.xml
lambdas/issuecredential/src/main/resources/log4j2.xml
lambdas/question/src/main/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandler.java
lambdas/question/src/main/resources/log4j2.xml

- Added log4j logging configuration
- Updated to use the latest EventProbe from common-lib

BAU - add logging config

---

infrastructure/lambda/template.yaml

Set Powertools metrics namespace globally for all functions.
Driving me to distraction.

BAU Set Powertools metrics namespace globally for all functions

---

infrastructure/lambda/template.yaml

Update expected aud from ipv core stub
- [KBV-533](https://govukverify.atlassian.net/browse/KBV-533)

KBV-533 Update expected aud from ipv core stub

---

lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/gateway/KeyStoreLoaderTest.java

Make tmp dir assertion work across operating systems

FIX make tmp dir assertion work across operating systems

---

infrastructure/lambda/private-api.yaml
infrastructure/lambda/template.yaml

Reverts alphagov/di-ipv-cri-kbv-api#81
VPC has been updated, so we're trying to use a private API gateway again

Revert "Revert "KBV-566 Add private api gateway""

---

infrastructure/lambda/template.yaml

- [KBV-XXXX](https://govukverify.atlassian.net/browse/KBV-XXX)

Read cv issuer param

---

lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java

Added condition to check for Error being sent by Experian endpoint
- [KBV-563](https://govukverify.atlassian.net/browse/KBV-563)

KBV-564: Send error from Experian IIQ Stub

---

infrastructure/lambda/template.yaml

SSM parameters to allow IPV Core to connect to KBV in production.
Signing verify JWK taken from the [prod passport CRI config](https://github.com/alphagov/di-ipv-config/blob/aef5f7127351a26fbdf422bdef444a457d4594eb/cris/passport/parameters/production.parameters.json#L31).
- [KBV-555](https://govukverify.atlassian.net/browse/KBV-555)

KBV-555 SSM params to configure IPV Core in Production

---

infrastructure/lambda/template.yaml

Add a new CRI client, `ipv-core-stub-pre-prod` for the KBV `production` environment.
Add config for the client `ipv-core-stub-pre-prod` as SSM Parameters that will be added in the prod environment only.
- [KBV-26](https://govukverify.atlassian.net/browse/KBV-26)

KBV-26 Add CRI client "ipv-core-stub-pre-prod"

---

infrastructure/lambda/private-api.yaml

Remove api key protection from private api

KBV-401 Remove api key protection from private api

---

infrastructure/lambda/template.yaml

FIX Import VPC endpoint id except for dev where the stack that exports the value does not exist yet.

🙃 FIX Import VPC endpoint id except for dev

---

infrastructure/lambda/template.yaml

Added SSM parameters for API Gateway ID and base URL
To break the hard dependency caused through using exports
- [KBV-511](https://govukverify.atlassian.net/browse/KBV-511)
Deployments will break production if the hard dependencies remain

KBV-511 introducce SSM parameters for API gateway

---

lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/StartAuthnAttemptRequestMapper.java

Log response from SAA (start authentication attempt) request
Getting errors from SAA and we want to figure out why.

BAU Log response from SAA (start authentication attempt) request

---

lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/StartAuthnAttemptRequestMapper.java

Log urn and authRefNo coming back from SAA response.
We are always getting an "Adress Not Found" outcome from third-party KBV supplier, so want to supply them with this data in order to track down the error.

BAU Log urn and authRefNo coming back from SAA response

---

infrastructure/lambda/template.yaml

Correct the pre-prod client issuer.
We updated this by hand, but need to set it permanently.

KBV-26 Correct the pre-prod client issuer

---

lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/StartAuthnAttemptRequestMapper.java

Reduce to one KBV address to mitigate receiving multiple of the same

GIX Reduce to one KBV address to mitigate receiving multiple of the same

---

infrastructure/lambda/template.yaml

Set session DDB ttl to 2 hrs, and VC JWT ttl the same

KBV-537 Set session DDB ttl to 2 hrs, and VC JWT ttl the same

---

infrastructure/lambda/template.yaml

Add provisoned concurrency in prod.
See the same PR on address CRI.

KBV-613 Add provisoned concurrency in prod

---

lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGateway.java
lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGatewayTest.java

Added missing test for when `getQuestion` method of KBVGateway class is called

BAU: More test coverage for KBVGateway

---

infrastructure/lambda/api.yaml
infrastructure/lambda/private-api.yaml

Reverts alphagov/di-ipv-cri-kbv-api#118

Revert "Revert "[KBV-619] add concurrency alias to arns""

---

infrastructure/lambda/api.yaml
infrastructure/lambda/private-api.yaml

Reverts alphagov/di-ipv-cri-kbv-api#119

Revert "[KBV-619] add concurrency alias to arns

---

lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/StartAuthnAttemptRequestMapper.java

Change log level from INFO to DEBUG in SAA request mapper

Set log level to debug for SAA

---

infrastructure/lambda/template.yaml
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGatewayFactory.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/StartAuthnAttemptRequestMapper.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/EnvironmentVariablesService.java
lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/gateway/StartAuthnAttemptRequestMapperTest.java
lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/util/TestDataCreator.java

Send a hardcoded gender to third-party API in non-prod environments as a workaround for an issue.

KBV-636 Add gender to IIQ Applicant if present as env var

---

infrastructure/lambda/public-api.yaml

Allow local dev to be easier by not requiring an API key on the public API.
This has been tested with an end-to-end journey on a local frontend and dev API stack.
- [KBV-689](https://govukverify.atlassian.net/browse/KBV-689)

KBV-689 Remove the OpenAPI security scheme in dev only

---

lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialService.java
lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java

* Set a metric at VC issue time indicating whether KBV passed or failed
* Add question id and strategy used dimensions to the metrics created in Question lambda
Here's the pass rate proportion after 1 pass and two fails. We can use this metric in Grafana too.
The question id and strategy used may be useful dimensions for helping diagnose issues for supporters.
- [KBV-691](https://govukverify.atlassian.net/browse/KBV-691)

KBV-691 CloudWatch metric for KBV pass or fail

---

infrastructure/lambda/template.yaml

Remove provisioned concurrency in prod as we need to amend our lambdas to deal with it.

FIx: Remove prov concurr in prod

---

infrastructure/lambda/template.yaml

KBV-700 Update KBV strategy

---

lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java
lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandler.java
lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialService.java
lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandlerTest.java
lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java

- Lambda functions updated to send user specific data
- As requested by the TxMA team
- [KBV-680](https://govukverify.atlassian.net/browse/KBV-680)

KBV-680 - send user-specific audit data to TxMA

---

infrastructure/lambda/template.yaml

Send Abandon lambda logs to Splunk. Please review by comparing to another subscription filter.
Add a subscription filter.
- [KBV-699](https://govukverify.atlassian.net/browse/KBV-699)

KBV-688 Send Abandon lambda logs to splunk

---

lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandler.java
lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialService.java

Add simple logging of credential issue outcomes. These logs should not be needed when we have a better understanding the cloudwatch metrics we produce.

BAU Add simple logging of credential issue outcomes

---

lambdas/abandon/build.gradle
lib/build.gradle

Add missing jacoco coverage to some gradle modules.
This will give us better stats in sonarcloud.

Add jacoco coverage

---

infrastructure/lambda/template.yaml

We want to test in Integration environment first see https://govukverify.atlassian.net/browse/OJ-830

OJ-830: Update to 3 out of 4 prioritised

---

.github/pull_request_template.md
.pre-commit-config.yaml
.secrets.baseline
README.md

Add pre commit config and read me updates.
Add a precommit hook to help stop secret leaks
- [OJ-928](https://govukverify.atlassian.net/browse/OJ-928)

OJ 928 Add secrets detect to backend

---

infrastructure/lambda/template.yaml

Set the IIQ strategy to `3 out of 4 prioritised` in all environment.
Now that we've tested the `3 out of 4 prioritised` in integration, and we've been notified that its been applied in prod, we can try test it in prod - outside normal daily operation hours.
- [OJ-943](https://govukverify.atlassian.net/browse/OJ-943)

OJ-943 Set strategy to "3 out of 4 prioritised" in all environments

---

.github/workflows/pre-merge-integration-test.yml

Removed the cron job setting from the pre-merge-integration tests

BAU - removed cron job from the pre-merge-integration tests

---

deploy.sh

Updated the deploy.sh for  to reflect the latest changes for common lambdas.
Due to changes in Pr: https://github.com/alphagov/di-ipv-cri-kbv-api/pull/170 the deploy script is updated with new parameters.
For easy deployment.

BAU: Updated deploy.sh

---

infrastructure/lambda/template.yaml

- Removed old log group subscription filters
- As requested by @instantiator 
- [OJ-1015](https://govukverify.atlassian.net/browse/OJ-1015)

OJ-1015 - remove old log group subscription filter

---

.github/workflows/pre-merge-integration-test.yml

build: delete pre-merge stack with aws cloudformation delete-stack. This deletes the stack asynchronously.
`sam delete` is timing out deleting stacks in cri-dev.

BAU build: delete pre-merge stack with aws cloudformation delete-stack

---

.github/workflows/pre-merge-integration-test.yml
lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java

Fix sonar smells on SessionHandler which were raised in https://github.com/alphagov/di-ipv-cri-kbv-api/pull/181.

style: fix sonar smells on QuestionHandler

---

.github/workflows/pre-commit.yml
.secrets.baseline

Add precommit GHA

---

README.md
integration-tests/src/test/java/gov/uk/kbv/api/stepDefinitions/APISteps.java
integration-tests/src/test/resources/features/KbvJwtLifespan.feature

We have added a test where we check if JWT lives for 2 hours.
We didn't have a scenario to test JWT lifespan before.
- [OJ-1039](https://govukverify.atlassian.net/browse/OJ-1039)
Check Readme.md

add JWT lifespan test

---

dependabot.yml

add dependabot config for Gha

---

lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactory.java
lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactoryTest.java

Reverts alphagov/di-ipv-cri-kbv-api#215 due to issues with SPoT

Revert "Revert "BAU: temporarily remove checkdetails""

---

infrastructure/lambda/template.yaml

- [OJ-1109](https://govukverify.atlassian.net/browse/OJ-1109)

Change VC expiry time to 6 months

---

lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactory.java
lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactoryTest.java

Spot is ready to test this in Staging
Reverts alphagov/di-ipv-cri-kbv-api#218

BAU: temporarily remove checkdetails

---

integration-tests/src/test/java/gov/uk/kbv/api/client/KbvApiClient.java
integration-tests/src/test/java/gov/uk/kbv/api/stepdefinitions/KbvSteps.java
integration-tests/src/test/resources/features/KbvApiHappyPath.feature
integration-tests/src/test/resources/features/KbvApiUnhappyPath.feature

User answers two questions incorrectly and fails verification test
Added new feature file `KbvApiUnhappyPath.feature`
- [OJ-1116](https://govukverify.atlassian.net/browse/OJ-1116)
[OJ-1116]: https://govukverify.atlassian.net/browse/OJ-1116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1116 - KBV API Unhappy Path scenario

---

README.md
integration-tests/build.gradle
integration-tests/src/test/java/gov/uk/kbv/api/runners/RunCucumberTest.java
integration-tests/src/test/java/gov/uk/kbv/api/stepdefinitions/KbvSteps.java
integration-tests/src/test/resources/allure.properties

We have added Allure reporting.
We did not have Allure reporting before.
OJ-1082

Oj 1082 allure reporting for kbv api

---

.github/workflows/pre-merge-integration-test.yml

Fix pipeline failures.
Pinned the Gradle version in the GitHub workflow.
To fix failures due to the workflow trying to use the latest version which is incompatible.
- [OJ-1243](https://govukverify.atlassian.net/browse/OJ-1243)
[OJ-1243]: https://govukverify.atlassian.net/browse/OJ-1243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OJ-1243] Fix-issues-with-pipeline-failing-due-to-gradle

---

.github/workflows/post-merge-deploy-to-dev.yml
.github/workflows/post-merge-package-for-build.yml
.github/workflows/pre-merge-integration-test.yml

- Updated SAM versions in post merge files
- Pinned Gradle version in post merge files
Fix workflows as failing in Main branch

Oj 1243 fix issues with pipeline failing due to gradle versions post merge

---

.github/workflows/post-merge-package-for-build.yml

Removed whitespace in a yml file
There was a white space in the yml file causing it to be invalid

OJ 1243 Invalid yaml file

---

infrastructure/lambda/private-api.yaml
infrastructure/lambda/public-api.yaml

Release TS lambdas

---

infrastructure/lambda/private-api.yaml
infrastructure/lambda/public-api.yaml

Revert TS lambdas release

---

infrastructure/lambda/private-api.yaml

Revert PR to use for quick restoration of previous variant of service if issues identified in production

Revert: "feat: Switch to using TS Session lambda"

---

infrastructure/lambda/private-api.yaml

This reverts commit b0826b81e94f3bbf71f20ba33384ebeeb37d54f4.
Restoration PR to use for after no obvious issues detected with service in production

Revert "Revert "feat: Switch to using TS Session lambda""

---

infrastructure/lambda/private-api.yaml

Restoration PR to use for after no obvious issues detected with service in production

Revert "Revert "feat: Switch to using TS Authorization lambda""

---

infrastructure/lambda/public-api.yaml

Switchover Access function to TypeScript version

feat: Switch to using TS Access lambda

---

infrastructure/lambda/public-api.yaml

This reverts commit 3cec77f8655900cbf564a7bbb2dd0f298d169870.
Revert PR to use for quick restoration of previous variant of service if issues identified in production

Revert "feat: Switch to using TS Access lambda"

---

infrastructure/lambda/public-api.yaml

Restoration PR to use for after no obvious issues detected with service in production

Revert "Revert "feat: Switch to using TS Access lambda""

---

lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/VerifiableCredentialConstants.java
lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactory.java
lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactoryTest.java
lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialServiceTest.java

OJ-1326 Add unable to authenticate

---

build.gradle
infrastructure/lambda/template.yaml
integration-tests/src/test/java/gov/uk/kbv/api/stepdefinitions/KbvSteps.java

Use release flag with vc expiry property.
See: https://github.com/alphagov/di-ipv-cri-lib/pull/208
- [OJ-1313](https://govukverify.atlassian.net/browse/OJ-1313)
[OJ-1313]: https://govukverify.atlassian.net/browse/OJ-1313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use release flag for vc expiry property

---

.github/workflows/pre-merge-integration-test.yml

change made to the code to allow perms for history

---

doc/api.puml

api.puml
There was an inconsistency to what was represented on the diagram to what actually happens.

Corrected status code at point 28 to be a 204

---

infrastructure/lambda/template.yaml

`template.yaml` increased rate limit related configs by a factor of 2.
During performance testing, ~90% of tests failed due to rate limit. 
- [OJ-1684](https://govukverify.atlassian.net/browse/OJ-1684)
[OJ-1684]: https://govukverify.atlassian.net/browse/OJ-1684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1684: Rate limiting

---

deploy.sh
integration-tests/src/test/java/gov/uk/kbv/api/stepdefinitions/KbvSteps.java

BAU: Configure ObjectMapper not to fail on unknown properties

---

.github/workflows/pre-merge-integration-test.yml

I duplicated the changes made in Address API to look at fixing the pre merge integration tests
Fix the failed testing

Make changes in KBV as they were in address

---

infrastructure/lambda/template.yaml

The rate limit was increased
The low volume performance testing failed due to http 429. This change was done to address and fixed the issue so it has been copied over to KBV.
- [OJ-1684](https://govukverify.atlassian.net/browse/OJ-1684)
[OJ-1684]: https://govukverify.atlassian.net/browse/OJ-1684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1684: Increased rate limits

---

.pre-commit-config.yaml
.secrets.baseline
CODEOWNERS
infrastructure/lambda/template.yaml

IPS-283 Added dynatrace lambda layer
Added cfn-lint and checkov to pre-commit config.
Fixed all of the issues highlighted in cfn-lint.
Updated CODEOWNERS
modified:   .pre-commit-config.yaml
modified:   .secrets.baseline
modified:   CODEOWNERS
modified:   infrastructure/lambda/template.yaml
IPS-283 Added dynatrace lambda layer
Added cfn-lint and checkov to pre-commit config.
Fixed all of the issues highlighted in cfn-lint.
Updated CODEOWNERS
- [IPS-283](https://govukverify.atlassian.net/browse/IPS-283)
[IPS-283]: https://govukverify.atlassian.net/browse/IPS-283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-283 Added dynatrace lambda layer

---

lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java

Reverts govuk-one-login/ipv-cri-kbv-api#295

Revert "OJ-1811-remove-unnecessary-code"

---

infrastructure/lambda/private-api.yaml

see: https://github.com/govuk-one-login/ipv-cri-common-lambdas/pull/279
Updating the private-api with 403 response on access denied

OJ-2346: Update authorization endpoint with 403 response

---

infrastructure/lambda/private-api.yaml

Accept new header in session endpoint
To align with changes in common lambdas
- [OJ-2504](https://govukverify.atlassian.net/browse/OJ-2504)
[OJ-2504]: https://govukverify.atlassian.net/browse/OJ-2504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2504: Accept new audit header in session endpoint

---

lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionState.java

To get better visibility of what's going see https://govukverify.atlassian.net/browse/OJ-2520
Will revert this PR once done, with analysing the issue

OJ-2520: Add some logging

---

integration-tests/src/test/java/gov/uk/kbv/api/client/KbvApiClient.java
integration-tests/src/test/java/gov/uk/kbv/api/stepdefinitions/KbvSteps.java
lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionState.java

Need more logging to view the questionState values When this issue occurs

OJ-2520: Need more logging to analyse issue

---

integration-tests/src/test/java/gov/uk/kbv/api/client/KbvApiClient.java
lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java
lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionState.java

OJ-2520: Extra logging

---

lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionState.java

Right now it is clear that the `question not found` was originally recorded
in the allQaPairs, the question should have been answered initially. Why is it
being asked again?
To investigate this further, more logging has been added

OJ-2520: more debugging

---

README.md
lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactory.java

Updates README and adds some comments

Updates README and adds some comments

---

README.md

BAU: Fix typo

---

infrastructure/lambda/template.yaml
jest.config.base.ts
jest.config.ts
package-lock.json
package.json
step-functions/fix-session-ttl.asl.json
step-functions/populate-session-table.asl.json
ts-lambdas/pii-redact/jest.config.ts
ts-lambdas/pii-redact/package.json
ts-lambdas/pii-redact/src/pii-redact-handler.ts
ts-lambdas/pii-redact/src/pii-redactor.ts
ts-lambdas/pii-redact/tests/pii-redact-handler.test.ts
ts-lambdas/pii-redact/tests/redact-pii.test.ts
ts-lambdas/pii-redact/tsconfig.json
ts-lambdas/sleep-function/jest.config.ts
ts-lambdas/sleep-function/package.json
ts-lambdas/sleep-function/src/sleep-function.ts
ts-lambdas/sleep-function/tsconfig.json
ts-lambdas/time-function/jest.config.ts
ts-lambdas/time-function/package.json
ts-lambdas/time-function/src/time-function.ts
ts-lambdas/time-function/tsconfig.json

Created 2 state machines **express** state machines. Express was chosen because they're much faster than standard state machines. During testing, to loop 250 records was taking around 6 seconds while express took 0.3 seconds. I calculated 250k would take 17 days if we use standard. Standard also cannot have more than 25,000 state transitions. During testing, this became an issue with a large amount of records causing the state machine execution to fail. With Express, it's unlimited.
**PopulateSessionStateMachine**
This state machine is used purely for generating mock records in the `person-identity-table` with an `expiryDate` of 7200 set. You can provide the following input to this state machine:
```
{
"amount": 100
}
```
Depending on the amount specified, that many records will be …

OJ-2638: Fix `expiryDate` TTL in `person-identity` table

---

.github/workflows/post-merge-package-for-build.yml

Added the workflow dispatch to workflow for build
Testing for OJ-2638 , to test that the log groups remain once we delete the stack in build
- [OJ-2638](https://govukverify.atlassian.net/browse/OJ-2638)
[OJ-2638]: https://govukverify.atlassian.net/browse/OJ-2638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added the workflow dispatch to workflow for build

---

.github/workflows/post-merge-package-for-build.yml

Reverts govuk-one-login/ipv-cri-kbv-api#373

Revert "Added the workflow dispatch to workflow for build"

---

lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandler.java
lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandlerTest.java

This PR relates to https://github.com/govuk-one-login/ipv-cri-kbv-api/compare/main...OJ-2652 pulling this out it.
In particular to: https://github.com/govuk-one-login/ipv-cri-kbv-api/commit/340d848f8d76e242c81f1c137e25f3e61b1f86d2
When using the accesstoken to retrieve the Session. If the Session is not found, has expired or the Access token has expired this would result in an AccessDenied Error
This is to adhere to contract testing patterns see https://github.com/search?q=repo%3Agovuk-one-login%2Fipv-core-back%20ccessTokenReturns403&type=code

OJ-2652: AccessDenied Error

---

lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KeyStoreLoader.java

Adjust getting the keystore from a temporary file

BAU: Adjust KeyStoreLoader

---

lambdas/abandon/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/AbandonKbvHandlerTest.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KeyStoreLoader.java
lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/gateway/KeyStoreLoaderTest.java

Reverts govuk-one-login/ipv-cri-kbv-api#406

Revert "OJ-785: Fix - remove unused result variable to remove code smell"

---

infrastructure/lambda/private-api.yaml
infrastructure/lambda/public-api.yaml
infrastructure/lambda/template.yaml

Reverts govuk-one-login/ipv-cri-kbv-api#420
See https://gds.slack.com/archives/C04RH15THAL/p1730721625257609 for context

Revert "Revert "IPS-1087: Update lambda canaries""

---

lib/build.gradle
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/security/HeaderHandler.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/security/SoapTokenRetriever.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/ServiceFactory.java
lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/util/SoapTokenUtils.java
lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/security/HeaderHandlerTest.java
lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/security/SoapTokenRetrieverTest.java
lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/util/SoapTokenUtilsTest.java

Reverts govuk-one-login/ipv-cri-kbv-api#448

Revert "Revert "OJ-2841: SOAP token""

---

build.gradle

bump cri-lib to 4.2.0
- [OJ-3087](https://govukverify.atlassian.net/browse/OJ-3087)
[OJ-3087]: https://govukverify.atlassian.net/browse/OJ-3087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

deps: bump cri-lib to 4.2.0

---

build.gradle

bump cri-lib to 5.2.1
- [OJ-3180](https://govukverify.atlassian.net/browse/OJ-3180)
[OJ-3180]: https://govukverify.atlassian.net/browse/OJ-3180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bump: cri-lib 5.2.1

---

infrastructure/lambda/template.yaml

Set Dynatrace logging vars per environment
To help debug segfault errors
- [OJ-3430](https://govukverify.atlassian.net/browse/OJ-3430)
[OJ-3430]: https://govukverify.atlassian.net/browse/OJ-3430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3430: Set Dynatrace logging vars per environment

---

infrastructure/lambda/template.yaml

Add logging vars to Question Handler
That's where we've been seeing more seg faults
- [OJ-3430](https://govukverify.atlassian.net/browse/OJ-3430)
[OJ-3430]: https://govukverify.atlassian.net/browse/OJ-3430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3430: Add logging vars to Question Handler
