- template.yaml
Add a new DynamoDB table to support the KBV credential issuer API.
See discussion of the table at https://govukverify.atlassian.net/browse/KBV-128.
There are no attribute definition for attributes that are not required for indexes i.e. the `questions` or `auth_ref_no`.
This has been SAM deployed to our DI IPV dev environment.
> KBV-128 Add kbv-session DynamoDB table

- api.yaml
- template.yaml
This PR is to incorporate the use of an Open Api definition for Api gateway endpoints.
It turns out that an s3 bucket is not actually required to link the Open Api definition to
the SAM template.
Open Api is more descriptive and can do stuff like validation, also provides a better description and documentaion of the use of the Api.
- [KBV-179](https://govukverify.atlassian.net/browse/KBV-179)
> KBV-179: openapi definition for the API gateway

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- README.md
- template.yaml
Update to enable GitHub actions deployments into the di-ipv-cri-dev AWS account.
* Added GitHub actions workflow for deployment on push to main after PR approval.
* Updated SAM template to include code signing.
To enable automated GitHub actions deployments into the di-ipv-cri-dev AWS account.
- [KBV-177](https://govukverify.atlassian.net/browse/KBV-177)
Required GitHub secrets inside and environment for added security:
| Secret | Description |
| ------ | ----------- |
| AWS_ROLE_ARN | Assumed role IAM ARN |
| AWS_PROFILE_PATH | Parameter Store path to the signing profile versioned ARN |
| AWS_ROLE_SESSION | Assumed Role Session ID
> [KBV-177] GitHub actions sam deploy

- .github/workflows/deploy.yml
Update workflow to use the GitHub di-ipv-cri-dev environment
Deployment workflow updated to use the GitHub di-ipv-cri-dev environment
So that the deployment will pick up the environment secrets
- [KBV-177](https://govukverify.atlassian.net/browse/KBV-177)
None
> [KBV-177] use github environment

- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/ExperianService.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/ExperianServiceTest.java
We should only be testing public methods, the two test removed
are implied by the other two left
Remove unneed test
We should only be testing public methods, the two test removed
are implied by the other two left
> BAU: Remove test on internal logic

- deploy/template.yaml
Added conditional code signing and permissions boundary to the template.
Both the code signing and permissions boundary is required for deployments to build and downstream
- [KBV-362](https://govukverify.atlassian.net/browse/KBV-362)
None
> [KBV-362] conditional global permission boundary and code signing

- deploy/template.yaml
Remove extra array entry in Permission Boundary
This cause stack deployment to fail on main
see: https://github.com/alphagov/di-ipv-cri-kbv-api/runs/6350736391?check_suite_focus=true
> BAU: Remove extra blank array entry

- deploy/template.yaml
Mark Sailes released a blog post describing how you can reduce cold
start times by setting the Java tiered compilation level. Setting this
global will make the change to all our kbv-api lambdas.
> BAU: Set Java tiered compilation level

- infrastructure/lambda/template.yaml
If the sam template gets a `CodeSigningConfigArn` as a parameter then use it.
Currently we never used a `CodeSigningConfigArn` in the dev environment, and this breaks the updated dev platform team secure pipeline that now requires a signer.
This change works for a dev that slings up a sam deploy - this PR will prove that the kbv dev pipeline can deploy the api stack. 
- [KBV-400](https://govukverify.atlassian.net/browse/KBV-400)
> KBV-400 Use code signing config arn if supplied, irrespective of environment

- infrastructure/lambda/template.yaml
Allow issue credential function to read PersonIdentityTable in DDB.
This is a policy that the Address CRI never needed as there are no user attributes to read out when creating the Address VC.
- [KBV-510](https://govukverify.atlassian.net/browse/KBV-510)
> KBV-510 Allow issue credential function to read PersonIdentityTable in DDB

- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialServiceTest.java
Fix error for mapping of List<Address> to Object[] to make compatible with Nimbus claimset
Nimbus and ClaimSets really do not like List<> passed to them as, when trying to parse things like Java 8 objects and times (LocalDate, LocalTime, Optional<> etc), it falls over as we're unable to pass through a custom ObjectMapper that we do elsewhere.
For this reason, we take matters into our own hands and use our own ObjectMapper to convert these to Object[] (essentially converting our classes into a Map using Jackson and injecting this into the ClaimSet as an array of Object
This (very loosely) tracks KBV-106, referenced below:
- [KBV-106](https://govukverify.atlassian.net/browse/KBV-106)
> [KVB-106] Fix error for mapping of List<Address> to Object[]

- infrastructure/lambda/template.yaml
- lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
- lambdas/question/src/main/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandler.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/config/ConfigurationConstants.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/KeyStoreService.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/KeyStoreServiceTest.java
* Remove hardcoded `/dev` prefix for secret names
* Evaluate stack name as prefix for secret name
ℹ️ I'll set these secrets for dev's stacks in `di-ipv-cri-dev` once approved, and pre-merge.
* The harcoded secret names starting with `/dev` are inappropriate for KBV accounts besides dev.
* We may want different stacks on an account referencing different secrets e.g. a url that points to a mock IIQ service.
- [KBV-510](https://govukverify.atlassian.net/browse/KBV-510)
> KBV-510 Prefix secrets with stack name only

- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/Evidence.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/EvidenceType.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/VerifiableCredentialConstants.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialService.java
- Drop @context
- evidence.type needs updating to “IdentityCheck“
- vc.type needs amending from “KBVCredential“ to “IdentityCheckCredential“
- Drop addressType from the address returned
The Verifiable Credential was outputting some additional or incorrect information, which did not match the RFC
- [KBV-512](https://govukverify.atlassian.net/browse/KBV-512)
> [KBV-512] Correct shape of Verifiable Credential

- lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
- lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java
- lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/TestData.java
Make `processQuestionRequest` return a Question instead of being a void method
`processQuestionRequest` now returns a Question if available or null
`processQuestionRequest` also mutated the state of the response object and returned void
- [KBV-508](https://govukverify.atlassian.net/browse/KBV-508)
tests that explicitly covers the `processQuestionRequest` method
> KBV-508: Refactor questionhandler to not return void

- infrastructure/lambda/api.yaml
- infrastructure/lambda/template.yaml
- lambdas/abandon/build.gradle
- lambdas/abandon/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/AbandonKbvHandler.java
- settings.gradle
This is an **initial PR** to add a /abandon endpoint to API Gateway, subsequent PR would set the status of KBV journey to "Abandon" in the KBV table
Expose an the /abandon endpoint, this will be called be KBV frontend client, when user decides to discontinue with KBV
A new lambda was added, that returns a 200 Ok response
This enables the user to discontinue the KBV journey see https://govukverify.atlassian.net/browse/KBV-543
- [KBV-543](https://govukverify.atlassian.net/browse/KBV-543)
> KBV-543: expose the abandon kbv api endpoint

- infrastructure/lambda/private-api.yaml
- infrastructure/lambda/template.yaml
Add a private AWS API Gateway accessible from the VPC endpoint id only. It configures access to the same API endpoints as the public API for now.
This will allow to check whether our Fargate frontend can use the private API, which we can configure in the frontend repo.
If so, we can make further API changes to bucket our endpoints into public and private APIs.
> KBV-566 Add private api gateway

- infrastructure/lambda/template.yaml
- lambdas/abandon/build.gradle
- lambdas/abandon/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/AbandonKbvHandler.java
- lambdas/abandon/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/AbandonKbvHandlerTest.java
This is the 2nd PR to the Abandon KBV which updates the KBVItem status to Abandoned, and creates the authorization code
see: https://github.com/alphagov/di-ipv-cri-kbv-api/pull/75
This PR updates the KBVItem status to `Abandoned` and creates the AuthorizationCode for the session linked to the KBV
/abandon endpoint with a post request using the session-id, that identifies the KBV journey, function then sets the status of KBV to `Abandoned` and sets the session authorization code
So as to ensure that users have the option to discontinue with KBV if they wish to do so
- [KBV-543](https://govukverify.atlassian.net/browse/KBV-543)
> KBV-543: abandon kbv api update kbv item to abandoned

- infrastructure/lambda/api.yaml
This PR addresses Required field validation on API Gateway endpoint
for answer endpoint
if you have the following payload body to the /answer endpoint
```
{
"questionId": "Q00036"
}
```
Currently, API gateway allows the request
Valid request should be:
```
{
"questionId": "Q00036"
"answer": "The answer"
}
```
> BAU: Required field validation on /answer endpoint

- infrastructure/lambda/template.yaml
Fixed the log groups for the public and private APIGWs.
Also:
* renamed the public `KBVApi` to `PublicKBVApi` to make it clearer that it is public
* renamed APIGW access log loggroup names to make them easier to find
* output and export the `PublicKBVApi` id and base url
- [KBV-533](https://govukverify.atlassian.net/browse/KBV-533)
> KBV-533 Fix the loggroup ref for public and private apigws

- infrastructure/lambda/api.yaml
- infrastructure/lambda/private-api.yaml
Added securitySchemes for api key to the token
and issuer endpoints see: https://github.com/alphagov/di-ipv-config/pull/735
Use stub API-KEY  
Added securitySchemes config to the `api.yaml` file with associated security attributes to `/token` and `/credential/issue`
endpoints
To ensure that API KEY is supplied when making request to the above endpoints
> KBV-401: Secure token and issuer endpoint

- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/exception/QuestionNotFoundException.java
- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
- lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/StartAuthnAttemptRequestMapper.java
We need to further observe what's in the response payload of experian
When there are no questions KBV should throw an error instead, of returning a badRequest
> Add error to logging

- lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
- lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandlerTest.java
- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
- lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java
- Update `common-lambdas` & `common-lib` git submodules to the latest versions
- Update `AuditService` invocation in the `QuestionHandler`, `QuestionAnswerHandler` and `IssueCredentialHandler` classes
In order to send audit event metadata to TxMA
- [KBV-567](https://govukverify.atlassian.net/browse/KBV-567)
> KBV-567 - Send audit event meta data

- acceptance-tests/journey/Dockerfile
- acceptance-tests/journey/run-tests.sh
- acceptance-tests/journey/src/test/java/uk/gov/di/ipv/cri/kbv/acceptancetest/journey/KBVJourneyTest.java
* [Add aws-cli to acceptance test image](https://github.com/alphagov/di-ipv-cri-kbv-api/commit/a074b2f249d94cf7004a716dfa05a96d01f4e2d1)
* [Relax assertion on number of expected answers on a KBV page](https://github.com/alphagov/di-ipv-cri-kbv-api/commit/3a1641c0cd2dd9ea0ad5ed6b3031da7c0f0a0736)
This was tested with:
````
cd acceptance-tests/journey
docker run -v $(pwd):/home/gradle/build/reports/tests -e PIPELINE_START_URL=xxxxxxxxx -e PIPELINE_BASIC_AUTH_USERNAME=xxxx -e PIPELINE_BASIC_AUTH_PASSWORD=xxxx --rm -it $(docker build -q .)
````
☝️ and this all runs clean and prints out the `aws-cli` version.
The AWS CodePipeline was failing as it expects the test container to have the aws-cli installed.
- [KBV-531](https://govukverify.atlassian.net/browse/KBV-531)
> KBV-531 Add aws-cli to acceptance test image

- lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
- lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java
- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
- lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/QuestionsResponse.java
see: https://govukverify.atlassian.net/browse/KBV-605
When making the first request is made, if the response is Insufficient questions and the experian session Ends.
When this outcome is encountered, the question lambda must:
- return a 204 status code to the KBV frontend. 
- write this outcome to the KBV DDB table as the status for this session
- Create an authorization code in the Session DDB table
The situation is as a result of users with a thin file i.e. they don't have a sufficient data with Experian and as a result there Experian KBV journey ends
Currently, the service errors, it should now be possible to generate a VC with a score of zero
and allow IPV CORE to continue alternate flow for the user
- [KBV-605](https://govukverify.atlassian.net/browse/KBV-605)
> KBV-605: Enable VC score of Zero for user with a thin file

- infrastructure/lambda/template.yaml
The question lambda needs the ability to write an auth code to DDB, and read txma-related data.
We made this change on a dev stack but forgot to commit this rather important bit to a previous PR.
The question lambda now has the ability to exit the user journey when we retrieve the first questions, so it needs to write an auth code to the session table, and read some data for a TxMA event.
- [KBV-605](https://govukverify.atlassian.net/browse/KBV-605)
> KBV-605 Add DDB read & write policy for QuestionFunction

- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGatewayFactory.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/ResponseToQuestionMapper.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/StartAuthnAttemptRequestMapper.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/MetricsService.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/gateway/ResponseToQuestionMapperTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/gateway/StartAuthnAttemptRequestMapperTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/MetricsServiceTest.java
Send result and error metrics to cloudwatch.
Add a new MetricsService that sends 4 metrics with dimensions:
1. initial_questions_response, dimensions: outcome, transId
2. initial_questions_response_error, dimensions: errorCode
3. submit_questions_response, dimensions: outcome, transId
4. submit_questions_response_error, dimensions: errorCode
Co-authored with @jkunle and @amanmsirius 
We need to get a better dashboard view of the results of IIQ API calls.
- [KBV-621](https://govukverify.atlassian.net/browse/KBV-621)
> KBV-621 send result and error metrics to cloudwatch

- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialServiceTest.java
- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
- lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java
A user with Insufficient initial questions to authenticate should be issued a verifiable credential with a verification score of zero.
The user experience at present is that the user sees a technical error page.
* [Send a verificationScore of 0 in all cases except when the result of …](https://github.com/alphagov/di-ipv-cri-kbv-api/commit/cbcab1bd3d0d9a53ae2133b465f1fbbaa219ef37)
* [set authorization code and TxMA event when there are no questions ret…](https://github.com/alphagov/di-ipv-cri-kbv-api/commit/8146b24193f709783c5090e9cc0970b90f0b8358)
* [return http status 204 on QuestionNotFoundException](https://github.com/alphagov/di-ipv-cri-kbv-api/commit/92e274a4e2701218853860f535446e2a5447ad98)
* [test for returning http status 204 on …
> KBV-605 User with insufficient questions gets a VC JWT

- infrastructure/lambda/template.yaml
Amended `template.yaml` to switch test database mode for Experian IIQ API to `Static`
As part of moving towards a more concrete UAT environment, changing the mode from `Aged` to `Static` for the `testDatabase` field in the payload
- [KBV-632](https://govukverify.atlassian.net/browse/KBV-632)
> Change IIQ API database mode from Aged to Static

- infrastructure/lambda/template.yaml
Don't use API keys in the `dev` environment.
✅ Checked on a dev stack.
This migitates the issue of the API key from core being shared across many stacks in dev:
````
The Usage Plan limit for  API Key core-ixxxxxxxx has been reached
````
Allow us to deploy however many stacks we wish to dev, using the same api key.
> FIX: Do not use the API key in dev

- infrastructure/lambda/template.yaml
- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
- lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionRequest.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/StartAuthnAttemptRequestMapper.java
We currently hardcode the IIQ Operator ID in the java code
We should move this to an SSM parameter on AWS so that it can be configured for any environment
Added new SSM in `template.yaml` called `IIQOperatorIdParameter`
- [KBV-640](https://govukverify.atlassian.net/browse/KBV-640)
> Add IIQ Operator id for Experian

- infrastructure/lambda/template.yaml
- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
- lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/StartAuthnAttemptRequestMapper.java
We currently hardcode the IIQ strategy into the KBV API as `3 out of 4`
We should move this to an SSM parameter on AWS so that it can be configured for any environment
Added new SSM in `template.yaml` called `IIQAPIStrategyParameter`
- [KBV-639](https://govukverify.atlassian.net/browse/KBV-639)
> Add IIQStrategy to AWS SSM

- infrastructure/lambda/template.yaml
The KBV APIGW used by KBV frontend is currently configured to be private, and only reachable from a client inside the same VPC.
This means we can’t have a dev frontend on localhost talk to the API.
Update config so that a localhost frontend can connect to a new dev-only APIGW.
* Add a new APIGW for dev only that covers the private API defintion
* Remove the need for an API key on the public APIGW in dev only
- [KBV-665](https://govukverify.atlassian.net/browse/KBV-665)
> KBV-665 Set api type to regional in dev environment

- infrastructure/lambda/template.yaml
Use [arm64 for better performance](https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/), and shift to more memory in higher environments.
Passport CRI has already  done it: https://github.com/alphagov/di-ipv-cri-uk-passport-back/blob/eb04b1a04a98987a5eb88d2d2bc108faf7e89105/deploy/template.yaml#L173-L175
> BAU Use ARM64 and change memory size per env

- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialService.java
Remove `kbv_pass` metric, replace with a dimension with the verification pass or fail fact.
We can look up these dimensions on the renamed `kbv_credentials_issued` metric.
> BAU Remove kbv_pass metric, replace with a dimension

- lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGatewayFactory.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/StartAuthnAttemptRequestMapper.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/security/KBVClientFactory.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/security/SoapToken.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGatewayTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/gateway/StartAuthnAttemptRequestMapperTest.java
By turning on lambda concurrency, the questionHandler lambda would be warm meaning that the configuration values would not be refreshed for running instances. This PR attempt to address this by ensuring config values are used at the point where they are needed and if possible not in the constructor
Inject the same configurationService instance into the services
We need the ability, to refresh configuration at runtime
- [KBV-705:](https://govukverify.atlassian.net/browse/KBV-705:)
> KBV-705: make question handler get secrets at runtime

- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGateway.java
see: https://govukverify.atlassian.net/browse/KBV-774
This annotation should help filter calls to the experian endpoints
in x-ray, this would help to filter x-ray by the requests types
see: https://docs.aws.amazon.com/xray/latest/devguide/xray-console-deeplinks.html#xray-console-deeplinks-filters
Add annotation when the call about to be made to experian
There is currently no way to search for the existing subsegment related to experian call 
- [KBV-774](https://govukverify.atlassian.net/browse/KBV-774)
> KBV-774: Add experian request annotation to filter x-ray

- .github/workflows/post-merge-package-for-build.yml
The test image included in the push to build has been removed.
The acceptance test image is now being pushed from a different repository and workflow. The test image included in the push to build is no longer required and breaks the deployment so needs to be removed.
- [KBV-778](https://govukverify.atlassian.net/browse/KBV-778)
None
> KBV-778 remove test image push from GH workflows

- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGateway.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/StartAuthnAttemptRequestMapper.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/MetricsService.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGatewayTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/MetricsServiceTest.java
Even though X-ray provides subsegments that show the actual duration of the request being investigated. There isn't an easy way to extract this information. This PR is needed to be able to capture the actual duration of the experian requests i.e. the request for question and the duration of the request when submitting answers
see: https://govukverify.atlassian.net/browse/KBV-774
Add more metric and logging for experian requests
More information required to the extract details at the level of the method call
It maybe that just logging would be enough, however added metric here as well if it proves not be useful would remove in future PR
> KBV-774: Capture duration of experian requests

- .github/workflows/pre-merge-integration-test.yml
- infrastructure/lambda/template.yaml
The sam template and GH pre-merge integration test workflow have been updated.
The code signing has been enforced in the secure pipelines for the new dev environments but optional opt out for the pre-merge integration tests and to allow developers to push.
- [OJ-801](https://govukverify.atlassian.net/browse/OJ-801)
Changes made as previously rolled out for address
> OJ-801 Update code signing config for dev environments

- infrastructure/lambda/template.yaml
The log groups have been renamed
These changes have been made to work around conflicts log group names with @clickopsed" log groups which is preventing the deployments downstream of build. 
- [OJ-822](https://govukverify.atlassian.net/browse/OJ-822)
Log group names can be reverted if required in a subsequent PR after existing log groups have been deleted or other-how renamed
PLEASE DO NOT MERGE!
> OJ-822 add and ref log groups

- infrastructure/lambda/template.yaml
Restore previous log groups configuration
Log groups configuration was not fully configured and logs written to old groups so temporarily restore old groups to ship logs to splunk. New updated log groups need to be enabled for deployment to a clean account but for existing accounts will need importing. 
- [OJ-822](https://govukverify.atlassian.net/browse/OJ-822)
Commented blocks left in which will need importing at a later date
> OJ-822 restore log groups

- lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
- lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/ContraIndicator.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/Evidence.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialServiceTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/KBVItem.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/KbvQuestionAnswerSummary.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionsResponse.java
V03 contra indicator should be generated if a user does not successfully complete the KBV challenge. This story applies to cases where the file has enough questions. 
There are two instances for which a V03 can occur when there are enough questions
1. The two initial questions asked were answered incorrectly, in this case this is already a failure, it would not be possible to request further questions as the `3 out of 4` has failed so V03 should be returned _(Note if the file had 3 questions the authentication status returned allow us to distinguish as it would be different from `Not Authenticated`)
2. One of the initial question was answered correctly in this case, further request would need to be made in other to see if the more question can be answered correctly. If one or more further …
> OJ-790: Generate v03 indicator for failed kbv attempts

- infrastructure/lambda/template.yaml
- lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
- lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java
- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
- lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/KBVAnswerItem.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/KBVAnswerStorageService.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/util/KBVAnswerStorageMapper.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/KBVAnswerStorageServiceTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/util/KBVAnswerStorageMapperTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/util/TestDataCreator.java
See [OJ-862](https://govukverify.atlassian.net/browse/OJ-862)
See also: https://github.com/alphagov/di-ipv-cri-lib/pull/44
Have a way of saving answers into answers dynamodb table
Addition of new table specifically for the purpose below
We need to record answers that Experian generate to the KBV questions.
We need to know what the answers are so we can analyse them for translation patterns.
These need to be kept somewhere safe and anonymised, completely unassigned to users or sessions. This is so that we can make an informed decision on:
How to un-capitalise the answers in the future (post-MVP)
How to handle translating answers into Welsh
- Part of [OJ-164](https://govukverify.atlassian.net/browse/OJ-164)
- Related to [OJ-861](https://govukverify.atlassian.net/browse/OJ-861)
> OJ-862: saving answers to dynamodb

- infrastructure/lambda/template.yaml
- Added an SSM parameter for the private api gateway id
- To remove the tight-coupling between the kbv-api stack and the dns-records/kbv-front stacks
- [OJ-953](https://govukverify.atlassian.net/browse/OJ-953)
> OJ-953 - add private api-gateway ssm parameter

- build.gradle
- lambdas/abandon/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/AbandonKbvHandler.java
- lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandler.java
- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
Log the the `govuk_signin_journey_id` when each lambda is called.
Logging of this id occurs via method invocations on the `SessionService` in the [cri-libs](https://github.com/alphagov/di-ipv-cri-lib) library.
This has been tested on a KBV stack deployed to `di-ipv-cri-dev`.
Added logging.
- [OJ-930](https://govukverify.atlassian.net/browse/OJ-930)
> OJ-930 log govuk_signin_journey_id in each lambda request

- infrastructure/lambda/template.yaml
Reverts alphagov/di-ipv-cri-kbv-api#173
After careful consideration, it has transpired that this change is no longer necessary.
The path to live for the new stack will now rely on the existing Export/ImportValue approach.
> Revert "OJ-953 - add private api-gateway ssm parameter"

- .github/workflows/post-merge-package-for-build.yml
- README.md
Updated secret names to be indicative of the account
For clarification in the growing number of github actions secrets
- [OJ-945](https://govukverify.atlassian.net/browse/OJ-945)
None
> oj-945 deploy common cri to build

- infrastructure/lambda/template.yaml
Add both old non python and new python subscription filters for splunk
Requirement to use the new python subscription filters but to keep the old filters to ensure no logs get lost
- [OJ-985](https://govukverify.atlassian.net/browse/OJ-985)
> OJ-985 update logging subscription filters

- .secrets.baseline
- README.md
- infrastructure/lambda/samconfig.toml.example
- infrastructure/lambda/template.yaml
- integration-tests/src/test/resources/cucumber.properties
CloudWatch Alerts on the following errors in the non-dev KBV accounts:
*  lambda errors for all lambdas in the account
* API Gateway 5XX errors for all APIGWs in the account
* API Gateway 4XX errors for all APIGWs in the account, with a slightly higher breach threshold
```mermaid
graph LR;
subgraph CloudWatch_Alarms[CloudWatch Alarms]
lambda_errors[lambda errors];
5xx_errors[5XX errors];
4xx_errors[4XX errors];
end
lambdas-- error event -->lambda_errors;
APIGW[API Gateway]-- 5XX event --> 5xx_errors;
APIGW-- 4XX event --> 4xx_errors;
lambda_errors-->AlarmTopic[SNS Alarm Topic];
5xx_errors-->AlarmTopic;
4xx_errors-->AlarmTopic;
AlarmTopic-->Email;
```
Alerts are delivered to an email mailing list. The email address is configured as an SSM parameter in the prod account by hand. @mrdoodles …
> feat: OJ-541 alert on lambda and APIGW errors and notify to email

- deploy.sh
In `deploy.sh` common stack name should be pointing to the local common api stack
> BAU: Change Common Stack name to local

- build.gradle
Proposed changes
As a consequence to
https://github.com/alphagov/di-ipv-config/pull/958
https://github.com/alphagov/di-ipv-stubs/pull/160
What changed
Stub are now verifiying the JWT from the VC
Why did it change
There is the need to verify that the JWT produce is coming from the expected party
> OJ-990: Use vc signing concat format

- infrastructure/lambda/template.yaml
For 5xx and 4x errors, use the sum of errors across the public and private API gateways.
Previously we used the sum of the API stage, and this didn't seem to work.
The sum expression e1 is the only metric with ReturnData: true so this is the single metric that makes up the alarm.
We've already landed this for Address with https://github.com/alphagov/di-ipv-cri-address-api/pull/224
ℹ️  Check that the `ApiName` value in this PR matches the api name for the API gateway resource.
- [OJ-1017](https://govukverify.atlassian.net/browse/OJ-1017)
> OJ-1017 KBV: sum API gateway errors across public and private gateways for Alarm

- .secrets.baseline
- README.md
- build.gradle
- infrastructure/lambda/template.yaml
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/VerifiableCredentialConstants.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialServiceTest.java
- Updated the VC JWT time-to-live to 6 months
- Updated to the latest version of `cri-common-lib`
- Removed redundant constants from the `VerifiableCredentialConstants` class
- Updated VerifiableCredentialService to use the new common `VerifiableCredentialClaimsSetBuilder` class
- There is a requirement to change the VC JWT time-to-live to 6 months
- There is unnecessary duplication of the logic to create the VC claims between the address, kbv & fraud CRIs
- [OJ-976](https://govukverify.atlassian.net/browse/OJ-976)
> OJ-976 - Extend VC JWT expiry & use common VC claims builder

- .github/workflows/pre-merge-integration-test.yml
- integration-tests/src/test/java/gov/uk/kbv/api/stepDefinitions/APISteps.java
- integration-tests/src/test/resources/features/KbvApiAbandonPath.feature
Add cucumber integration test to the `di-ipv-cri-kbv-api` for `abandon` end point
- Added new `feature` file for Abandon end point
- New steps added to the `APISteps` file
- [OJ-1025](https://govukverify.atlassian.net/browse/OJ-1025)
To run the tests:
`STACK_NAME=di-ipv-cri-kbv-api-xxxx API_GATEWAY_ID_PRIVATE=xxxx API_GATEWAY_ID_PUBLIC=xxxx IPV_CORE_STUB_BASIC_AUTH_USER=user IPV_CORE_STUB_BASIC_AUTH_PASSWORD=xxxx IPV_CORE_STUB_URL="https://di-ipv-core-stub.london.cloudapps.digital" APIGW_API_KEY=xxxx gradle cucumber -P tags=@pre_merge_abandon`
To run all tests:
`STACK_NAME=di-ipv-cri-kbv-api-xxxx API_GATEWAY_ID_PRIVATE=xxxx API_GATEWAY_ID_PUBLIC=xxxx IPV_CORE_STUB_BASIC_AUTH_USER=user IPV_CORE_STUB_BASIC_AUTH_PASSWORD=xxxx IPV_CORE_STUB_URL="https://di-ipv-core-stub.london.cloudapps.digita …
> OJ-1025: Add Abandon end point integration test

- .github/workflows/post-merge-deploy-to-dev.yml
- .github/workflows/post-merge-package-for-build.yml
- Removed unnecessary `./gradlew build` command from post-merge GHA workflows
- It is not necessary to manually invoke `gradle build` as the cide compilation and test execution is handled by `sam build`
> BAU - GHA - remove unnecessary build step from post-merge workflows

- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandlerTest.java
- Updated the `IssueCredentialHandler` class to send the `END` audit event
- As requested by the txma team
- [OJ-960](https://govukverify.atlassian.net/browse/OJ-960)
> OJ-960 - Send END audit event

- .secrets.baseline
- infrastructure/lambda/template.yaml
- lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
- lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/CheckDetail.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/Evidence.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/KbvQuality.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/VerifiableCredentialConstants.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactory.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandlerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactoryTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialServiceTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/fixtures/TestFixtures.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionState.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionStateTest.java
see: https://govukverify.atlassian.net/browse/OJ-937
This is PR only expands the evidence node of the VC output to included the attributes below
it uses and the associated mapping https://govukverify.atlassian.net/browse/OJ-1041 to specify the kbvQuality of the each question
This add as many checkDetails objects as are answered questions
and as many failedCheckDetails as are wrong questions to the
evidence node of the returned VC. 
[NA Questions ](https://docs.google.com/spreadsheets/d/11OYj42HWi7bL0rXm0HmEkyDxjqty9xDVHyuLwa48do4/edit#gid=0)are either questions that have been deem not suitable for
KBV but are to be returned as LOW quality questions.
We currently have a mix of LOW and MEDIUM quality questions.
NA Questions question in the mapping have value Zero. We are not sure if we need …
> Oj-937: add check details to vc response

- infrastructure/lambda/private-api.yaml
Added open-api validation for X-Forwarded-For header
See https://github.com/alphagov/di-ipv-cri-lib/pull/35
Needed for AuditService
> BAU: Add X-Forwarded-For header to api definition

- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactory.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactoryTest.java
Reverts alphagov/di-ipv-cri-kbv-api#214
Restores `checkDetails` functionality
> Revert "BAU: temporarily remove checkdetails"

- README.md
- deploy.sh
This PR allows the deploy script to be receive a different common api stack and to specify a different secret prefix if required without having to change the deploy script itself.
The local `deploy.sh` script
To prevent custom changes to `deploy.sh` to be pushed
> BAU: parameterise deploy script

- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
- lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java
(https://docs.google.com/spreadsheets/d/1cLjAdRcpw94uYLnrt7FTeFX5XM_7MLRTDWdf-Zbobj8/edit#gid=2084726467)
“there are a couple of fields the Billing and Transaction Monitoring Team are expecting to see in the payload that aren't there yet:
component_id
user.transaction_id
Acceptance criteria
can see component_id being sent in payload
can see user.transaction_id being sent in payload
TXMA confirmed they are happy
- [OJ-1121](https://govukverify.atlassian.net/browse/OJ-1121)
[OJ-1121]: https://govukverify.atlassian.net/browse/OJ-1121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1121: Add component-id to ipv-cri-request-sent

- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactory.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactoryTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialServiceTest.java
Logic has been added so that when a user is asked 3 questions and gets 1 incorrect a contra-indicator is returned
This means that scenario C in this document successfully returns a contra-indicator
https://github.com/alphagov/digital-identity-architecture/blob/main/adr/0049-insufficient-questions-contra-indicator.md#addition-of-contra-indicators
- [OJ-1326](https://govukverify.atlassian.net/browse/OJ-1326)
[OJ-1326]: https://govukverify.atlassian.net/browse/OJ-1326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1326 include missing contra-indicator

- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactory.java
Changes to cover 3 question scenario, either when the first 2 are answered correctly and the last question incorrect
or the case where the 1st two questions asked are incorrect Experian Session is terminated. The latter currently doesn't record a contraindicator as expected we want this and this is what this PR does.
The second scenario above behave yeilds an insufficent questions scenario, we have observed so far that this is the only instance we get a 2 question failed and a subsequent request that an insufficent questions  request to Experian, because we have recorded those 2 question we can assign a contraindicator. The inference here is that thin-file situation i.e a user with initially 2 or less question would immediately yeild an insufficient question scenario and because we don't …
> OJ-1326: 2 or less not observed

- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactory.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialServiceTest.java
Fix error logic introduced in https://github.com/alphagov/di-ipv-cri-kbv-api/pull/248
Change to address 3 question scenario see https://govukverify.atlassian.net/browse/OJ-1326
Conditional logic introduced bounds in an attempt to be more explicit about question size
- [OJ-1326](https://govukverify.atlassian.net/browse/OJ-1326)
[OJ-1326]: https://govukverify.atlassian.net/browse/OJ-1326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BAU: Fix conditional logic in KBV

- README.md
- build.gradle
Facilitate the ability to run the command https://github.com/alphagov/di-ipv-cri-kbv-api#run-integration-tests by changing IPV_CORE_STUB_URL to point to the new aws stub url i.e. https://cri.core.build.stubs.account.gov.uk
In moving from PAAS to AWS, new client needed to be created, the current pre-merge test would need to be flexible enough to ensure the stub client Id can be overriding with the expected one.
Work involving moving from PAAS to AWS
- [OJ-1522](https://govukverify.atlassian.net/browse/OJ-1522)
New Env variable DEFAULT_CLIENT_ID 
Updated [README](./blob/main/README.md) 
`ENVIRONMENT=xxxx STACK_NAME=xxxx IPV_CORE_STUB_CRI_ID=kbv-cri-dev API_GATEWAY_ID_PRIVATE=xxxx API_GATEWAY_ID_PUBLIC=xxxx IPV_CORE_STUB_BASIC_AUTH_USER=xxxx IPV_CORE_STUB_BASIC_AUTH_PASSWORD=xxxx …
> OJ-1522: Ensure integration tests works with AWS Core stub in KBV CRI

- .github/workflows/pre-merge-integration-test.yml
`pre-merge-integration.yml` changed `IPV_CORE_STUB_URL` to `https://cri.core.build.stubs.account.gov.uk` and added `DEFAULT_CLIENT_ID`
PaaS to AWS
- [OJ-1534](https://govukverify.atlassian.net/browse/OJ-1534)
[OJ-1543]: https://govukverify.atlassian.net/browse/OJ-1543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-1534]: https://govukverify.atlassian.net/browse/OJ-1534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1534: Added DEFAULT_CLIENT_ID and updated IPV_CORE_STUB_URL

- .secrets.baseline
- build.gradle
- infrastructure/lambda/template.yaml
Use release-flag for `vc-contains-unique-id` for kbv-cri implemented by https://github.com/alphagov/di-ipv-cri-lib/pull/244
Added release_flag for vc-contains-unique-id setting it to true In Dev
see: https://github.com/alphagov/digital-identity-architecture/blob/main/adr/0079-unique-identifier-for-verifiable-credential.md#option-6---preferred-optionIn order to be able to distinguish one Verifiable Credential (VC) from another VC it will be necessary for VCs to be able to be uniquely identifiable
- [OJ-1422](https://govukverify.atlassian.net/browse/OJ-1422)
This PR is dependent on version 1.5.1 of the below
- see https://github.com/alphagov/di-ipv-cri-lib/pull/244
[OJ-1422]: https://govukverify.atlassian.net/browse/OJ-1422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …
> OJ-1422: Add release_flag for vc-contains-unique-id

- infrastructure/lambda/template.yaml
VC Contain Unique Id enabled up to staging 
Included a unique identifier within the jti (JSON Web Token ID) claim representing a VC
Added release_flag for `vc-contains-unique-id` this can be enabled by setting the environment flag to true in the template file. Below all env(s) up to staging have been enabled
```
VcContainsUniqueIdMapping:
Environment:
dev: "true"
build: "true"
staging: "true"
integration: "false"
production: "false"
``` 
- [jti in context of a VC](https://github.com/alphagov/digital-identity-architecture/blob/7c90be0db85a3a3093c766d845d5f278a3d86e16/rfc/0045-claimed-identity-cri.md?plain=1#L217)
- [ADR 0079 Unique identifiers for verifiable credentials](https://github.com/alphagov/digital-identity-architecture/blob/7c90be0db85a3a3093c766d845d5f278a3d86e16/adr/0079-unique-i …
> OJ-1422: VC Contain Unique Id enabled up to staging

- lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
- lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java
- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
- lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java
`QuestionAnswerHandler.java`, `QuestionHandler.java` and accompanying unit tests.
Specifically, changed references to `AuditEventType.THIRD_PARTY_REQUEST_ENDED` to `AuditEventType.RESPONSE_RECEIVED`
TXMA are requesting we change the name of "IPV_KBV_CRI_THIRD_PARTY_REQUEST_ENDED" to "IPV_KBV_CRI_RESPONSE_RECEIVED". This is for consistency with passport CRI.
- [OJ-1105](https://govukverify.atlassian.net/browse/OJ-1105)
[OJ-1105]: https://govukverify.atlassian.net/browse/OJ-1105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1105: Updated audit event from "THIRD_PARTY_REQUEST_ENDED" to "RESPONSE_RECEIVED"

- lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
- lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java
- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
- lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java
Removed THIRD_PARTY_REQUEST_ENDED audit event
Requested by txma to be consistent with passport. As per their process, the new event was added in a separate PR and now that confirmation has been received, this PR is to now remove the old THIRD_PARTY_REQUEST_ENDED audit event. 
- [OJ-1150](https://govukverify.atlassian.net/browse/OJ-1150)
[OJ-1150]: https://govukverify.atlassian.net/browse/OJ-1150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1105: Removed THIRD_PARTY_REQUEST_ENDED

- lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
- lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java
see: https://govukverify.atlassian.net/browse/OJ-1055
It appears the event was only triggered when there are no questions returned from the call from Experian. The event should be triggered no matter the outcome of the Experian call.
Trigger `response_recieved` event when the call from Experian resulted in a questionResponse that contains questions
The above
Trigger `response_recieved` event only triggered when the call from Experian resulted in a no questions available scenario
- [OJ-1055](https://govukverify.atlassian.net/browse/OJ-1055)
[OJ-1055]: https://govukverify.atlassian.net/browse/OJ-1055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1055: send response received event on question availability

- lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
- lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java
see: https://govukverify.atlassian.net/browse/OJ-1055
The event was only currently triggered in the QuestionHandler, however we need to send the event before submitting answers in the QuestionAnswerHandler
Trigger `REQUEST_SENT` event just before submitting answers
The above
Trigger `REQUEST_SENT`  event in the `QuestionAnswerHandler`  which also a request to a Third party
- [OJ-1055](https://govukverify.atlassian.net/browse/OJ-1055)
[OJ-1055]: https://govukverify.atlassian.net/browse/OJ-1055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1055: add missing request sent event to question Answer handler

- infrastructure/lambda/template.yaml
What changed
Removed 4XX alarm from template
Why did it change
So that we are no longer running P1 alerts for 400's in production
> OJ-2075: Remove 4XXX alarm

- infrastructure/lambda/template.yaml
Rate Limits in the Usage Plan
HTTP 429s occurred during the performance testing. The usage plan had a smaller burst limit than what was set as the limits for the API gateway. By design, AWS uses the lower value between the Usage Plan and API Gateway. This PR sets them to both be the same.
- [OJ-2113](https://govukverify.atlassian.net/browse/OJ-2113)
[OJ-2113]: https://govukverify.atlassian.net/browse/OJ-2113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2113: Increased usage plan to match APIGW limits

- .github/workflows/pre-merge-integration-test.yml
- .secrets.baseline
Added `workflow_dispatch` to pre-merge-integration tests action so that we can manually trigger this without needing to raise a PR
> BAU: Added workflow_dispatch

- build.gradle
- settings.gradle
By default, SonarCloud sets the project name based on the gradle project name, so set it to the new value post-migration.
> OJ-2209: Update project name

- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
In the Experian API, there is just one call to the `/SAA` endpoint i.e getQuestions and multiple calls to `/RTQ` endpoint i.e submitAnswers
This [code](https://github.com/govuk-one-login/ipv-cri-kbv-api/pull/295/files#diff-88f028988d98316335066950a4387f73c4f3c0a7dd782b1420507d88d46d4358L245-L250) has been hanging around for a while, and causes confusion
- [OJ-1811](https://govukverify.atlassian.net/browse/OJ-1811)
[OJ-1811]: https://govukverify.atlassian.net/browse/OJ-1811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1811-remove-unnecessary-code

- lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialServiceTest.java
- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
- lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/KbvResponsesAuditExtension.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionsResponse.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/KBVService.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/domain/KbvResponsesAuditExtensionTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/util/TestDataCreator.java
Modify  event IPV_KBV_CRI_VC_ISSUED event to capture outcome of questions
Before: 
```
{
"timestamp": 1685458522,
"event_name": "IPV_KBV_CRI_VC_ISSUED",
"component_id": "https://review-k.dev.account.gov.uk",
"user": {
"user_id": "urn:fdc:gov.uk:2022:36509924-997d-40db-8eb1-7b7d9588d6d0",
"ip_address": "xx.xxx.x.x",
"session_id": "d853a50d-c913-4466-9f20-9b902bfa7fa9",
"persistent_session_id": "03ab21b9-df3d-4a41-9750-8219d661bc0c",
"govuk_signin_journey_id": "7a0xx9d2-4494-4a82-8xx8-5e6bd471e31b"
},
"extensions": {
"evidence": [
{
"txn": "8FCLCRTCZQ",
"verificationScore": 2,
"checkDetails": [
{
"checkMethod": "kbv",
"kbvResponseMode": "multiple_choice",
"kbvQuality": 2
},
{
"checkMethod": "kbv",
"kbvResponseMode": "multiple_choice",
"kbvQuality": 3
},
{
"checkMethod": "kbv", …
```
> OJ-2241: extend vc issued with kbv outcomes

- build.gradle
cri_common_lib to version 1.5.6
event_timestamp_ms related changes.
- [OJ-2291](https://govukverify.atlassian.net/browse/OJ-2291)
[OJ-2291]: https://govukverify.atlassian.net/browse/OJ-2291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2291: cri_common_lib version to latest

- infrastructure/lambda/template.yaml
- lambdas/abandon/build.gradle
- lambdas/abandon/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/AbandonKbvHandler.java
- lambdas/abandon/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/AbandonKbvHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/IIQAuditEventType.java
[OJ-2277] Add event IPV_KBV_CRI_ABANDONED
https://govukverify.atlassian.net/browse/OJ-2277
creating permissions to allow sending of sqs messages, audit Queue permissions and verifiable-credential
updating Gradle configurations
implemented auditing into AbandonKbvHandler, and updated the IIQAuditEventType to contain the abandoned type.
to allow the data analytics team to correctly calculate metrics
- [OJ-2277](https://govukverify.atlassian.net/browse/OJ-2277)
[OJ-2277]: https://govukverify.atlassian.net/browse/OJ-2277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-2277]: https://govukverify.atlassian.net/browse/OJ-2277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2277  Add event IPV_KBV_CRI_ABANDONED

- .github/workflows/check-pr.yml
- .github/workflows/deploy-branch.yml
- .github/workflows/post-merge-deploy-to-dev.yml
- .github/workflows/post-merge-package-for-build.yml
- .github/workflows/run-integration-tests.yml
- .github/workflows/run-unit-tests.yml
- .github/workflows/scan-repo.yml
- .gitignore
- build.gradle
- deploy.sh
- infrastructure/lambda/template.yaml
- integration-tests/build.gradle
- integration-tests/src/test/java/gov/uk/kbv/api/client/KbvApiClient.java
- integration-tests/src/test/java/gov/uk/kbv/api/stepdefinitions/KbvSteps.java
- integration-tests/src/test/resources/features/KbvApiAbandonPath.feature
- integration-tests/src/test/resources/features/KbvApiHappyPath.feature
- integration-tests/src/test/resources/features/KbvApiUnhappyPath.feature
**OJ-2545: Add CloudFront integration tests**
**Tests**
- Check for the device information header in the CRI start message
- Use the SQS and CloudFormation helpers from common-lib
- Update GHA to run the new integration tests
Run integration tests sequentially between PRs to avoid SQS concurrency issues.
- Use `JsonPointer` to make assertions for JSON objects
- Exclude the XRay package so tests can run wihtout having to intialise XRay tracing and segments
- Upgrade the version of the common-lib to get the SQS and CF helper
Update the AWS SDK version to match.
**Fixes**
- Use prefixed TxMA exports
The non-prefixed exports are deprecated and will be removed in the future.
- Use the correct secret prefix for local developer stacks
- Ignore `.env` file to allow to set env vars for local …
> OJ-2545: Add CloudFront header tests

- lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
- lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java
- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionAnswer.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionAnswerPair.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionAnswerRequest.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionState.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionsResponse.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionStateTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/util/TestDataCreator.java
When Resubmission occurs,  the next question should be return instead of an exception.
If there is no recorded store for an the answered question throw the IllegalStateException.
Logging revealed likelyhood of resubmissions i.e could be because of the following:
- The user pressed the back button and the state did not update causing them to see the previous question again.
- They re-submitted the KBV answer because the page could have been slow
- Lost connection during submission
- Duplicated the browser tab so the previous question was still available to them
When attempting the to save an answer, for resubmission it is logged instead of throwing an error nothing is done further
https://github.com/govuk-one-login/ipv-cri-kbv-api/blob/main/lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv …
> OJ-2520: Implement Fix

- build.gradle
To prevent against No such field errors. 
We use nimbus in the issue credential lambda
could find instances of the error in splunk logs for KBV
it could be that the interaction that lead to this error happening in postcode lookup
hasn't happen yet here. Postcode lookup has a more complex data objects to parse.
In any case it good to the version updated
see: https://github.com/govuk-one-login/ipv-cri-address-api/pull/999
> OJ-2525: Update nimbus to version in common-lib

- build.gradle
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/Evidence.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactory.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandlerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactoryTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialServiceTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/util/EvidenceUtils.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/util/EvidenceUtilsTest.java
This is approach 2 passing the SessionItem
The `verification_score` property within a VC is now fetched from the SessionItem in DynamoDB. If there is no evidence block in the session item then the default value of 2 will be used.
We now have multiple levels of confidence that has to be accurately reflected in the VC.
- [OJ-2612](https://govukverify.atlassian.net/browse/OJ-2612)
[OJ-2612]: https://govukverify.atlassian.net/browse/OJ-2612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2612: Use correct verification score in VC (Approach 2)

- build.gradle
- integration-tests/src/test/resources/features/KbvApiHappyPath.feature
Added another integration test scenario for going through the journey when the verificationScore is set to 1
To enable testing for low confidence journey
- [OJ-2612](https://govukverify.atlassian.net/browse/OJ-2612)
[OJ-2612]: https://govukverify.atlassian.net/browse/OJ-2612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2612: Add integration test scenario for low confidence journey

- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactory.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactoryTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionState.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/strategy/KbvStrategyParser.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/strategy/Strategy.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/util/EvidenceUtils.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionStateTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/strategy/KbvStrategyParserTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/util/EvidenceUtilsTest.java
Aim to reuse, existing logic as much as possible by having the ability to specify in Unit test each strategy
Please pay attention to [EvidenceFactoryTest](https://github.com/govuk-one-login/ipv-cri-kbv-api/pull/352/files)
The test here are categorized into 3 areas:
- Test about Evidence **Verification Score**
- Test about the **Authentication Status**
- Test about **EvidenceCheckDetails**
What to be able to swap out the strategy mode of operation of the EvidenceFactory, A new StrategyParser class has been added to enable this. It takes as input the strategy i.e
**Low confidence: "2 out of 3 Prioritised"
Medium confidence: "3 out of 4 Prioritised"**
By default the Strategy is set in the constructor of the EvidenceFactory to "3 out of 4 Prioritised" this is what we currently support. …
> OJ-2643: add low confidence unit test (part 1)

- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/builder/CheckDetailsBuilder.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/builder/steps/BuildTo.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/builder/steps/CreateCheckDetailsWithKbvQuality.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/builder/steps/Init.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/builder/steps/QuestionIdsInAllBatches.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/builder/steps/Skip1stQuestionIdIn2ndBatch.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/builder/steps/SortByKbvQuality.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/builder/steps/UnSkippedQuestionIdsInAllBatches.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactory.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/builder/CheckDetailsBuilderTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactoryTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialServiceTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionState.java
see: https://govukverify.atlassian.net/browse/OJ-2643
1. Renamed methods in EvidenceFactory, so it is readable and more understandable
2. Moved comments to the top of the method, it can be removed entirely in future or maybe moved to readme.
Introduced a  CheckDetailsBuilder to wrap the intricate logic in a named fluent interface of methods the are easier to understand
The Builder implements a `StepBuilder` pattern
inspired from
https://java-design-patterns.com/patterns/step-builder/#detailed-explanation-of-step-builder-pattern-with-real-world-examples-1
This is to ensure that methods that make sense are callable, from each step, essentially guiding the implementer of the logic when it is used, and preventing future missuse
After `createCheckDetailsWithKbvQuality()` the next likely steps …
> OJ-2643: Improving naming in EvidenceFactory

- build.gradle
- lambdas/abandon/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/AbandonKbvHandler.java
- lambdas/abandon/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/AbandonKbvHandlerTest.java
- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
- lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java
Bumped cri_common_lib (2.2.3 -> 2.3.0) to include requested_verification_score in log keys
Added requested_verification_score to the question_strategy metric. 
Modified AbandonLambda to validate session, which includes the logic for setting requested_verification_score log keys .
Refactored shouldReturn200OkWhen1stCalledAndReturn1stUnAnsweredQuestionFromExperianEndpoint test to remove code smell
As a developer,
I want to update the performance metrics to distinguish between Medium and Low confidence KBV challenges and log these metrics with the associated journey ID,
so that the system can accurately track and report on the performance of different confidence level challenges.
- [OJ-2619](https://govukverify.atlassian.net/browse/OJ-2619)
[OJ-2619]: …
> OJ:2619 Add verification score to logs and metrics

- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactory.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialServiceTest.java
Remove unused code segments i.e `getKbvQualityMapping` and unnecessary filter on `withoutKbvQuality`
Added 2 out of 3 prioritised test data to existing `shouldReturnASignedVerifiableCredentialJwt` which only had
3 out of 4 prioritised test data.
Stopped using deprecated constructor  `PersonIdentityDetailed(List.of(name), List.of(birthDate), List.of(address));`
- [OJ-2607](https://govukverify.atlassian.net/browse/OJ-2607)
[OJ-2607]: https://govukverify.atlassian.net/browse/OJ-2607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2607: miscellenous

- integration-tests/src/test/java/gov/uk/kbv/api/stepdefinitions/KbvSteps.java
- integration-tests/src/test/resources/features/KbvApiHappyPath.feature
- integration-tests/src/test/resources/features/KbvApiUnhappyPath.feature
Update existing integration tests for the VC to assert on `checkDetails` and `failedDetails` based on the test scenario so that we aren't solely reliant on the verification score.
To further coverage in integration tests.
- [OJ-2685](https://govukverify.atlassian.net/browse/OJ-2685)
[OJ-2685]: https://govukverify.atlassian.net/browse/OJ-2685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2685: Update integration test to validate VC details

- .github/workflows/post-merge-deploy-to-dev.yml
- .github/workflows/post-merge-package-for-build.yml
Unpin SAM version as it does not have the latest features that are needed for our changes. 
See: https://github.com/govuk-one-login/ipv-cri-kbv-api/actions/runs/9938145331
> BAU: unpin sam version

- package-lock.json
- package.json
Removed unused aws-sdk 2.x dependency
AWS has announced that [AWS SDK for JavaScript v2](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) will enter maintenance mode on September 8, 2024
- [OJ-2660](https://govukverify.atlassian.net/browse/OJ-2660)
[OJ-2660]: https://govukverify.atlassian.net/browse/OJ-2660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2660: Remove aws-sdk 2.x dependency

- integration-tests/src/test/java/gov/uk/kbv/api/stepdefinitions/KbvSteps.java
- integration-tests/src/test/resources/features/KbvApiHappyPath.feature
Updated the low confidence tests to assert the new  `"extensions": { "evidence": [ { "context": "identity_check", } ] "evidence_requested": { "verficationScore": "1", ... } }` work that has been added is visible in the start message.
To ensure the correct data is being sent for the start message.
- [OJ-2621](https://govukverify.atlassian.net/browse/OJ-2621)
[OJ-2621]: https://govukverify.atlassian.net/browse/OJ-2621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2621: Updated tests to include extensions work for low confidence

- build.gradle
- lambdas/abandon/build.gradle
- lambdas/abandon/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/AbandonKbvHandler.java
- lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialService.java
- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
- lib/build.gradle
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/ServiceFactory.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/ServiceFactoryTest.java
cri-lib to version 3.0.2
As part of the upgrade, I have created a `ServiceFactory` class which encapsulates all the AWS Clients and service objects that we have. Primary purpose is to avoid duplication and to keep the code clean.
To keep us up to date with the latest common-lib changes. 
- [OJ-2713](https://govukverify.atlassian.net/browse/OJ-2713)
[OJ-2713]: https://govukverify.atlassian.net/browse/OJ-2713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2713: Upgrade cri-lib to version 3.0.2

- step-functions/fix-session-ttl.asl.json
- ts-lambdas/time-function/src/time-function.ts
The Time Function is now returning epoch time in Unix timestamps in seconds rather than milliseconds.
The state machine will now update any records that have an expiry date greater than `1721520000000` i.e. 30/07/2025 - I have chosen this date specific as it won't affect the correct session records but fix the broken ones which are in the year 50k
We set the expiryDate TTL to epoch milliseconds instead of epoch seconds which caused the TTL value to be many many years into the future.
> Fix TTL state machine

- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/VerifiableCredentialConstants.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialServiceTest.java
Add @context to Experian VC, this is a change in the VC, while SPOT think this change would be breaking. They advice testing this in staging first. 
Currently 
```
{
"sub": "urn:fdc:gov.uk:2022:23657d7a-bc6a-4727-a8ca-9639f1a8f9bc",
"nbf": 1723127088,
"iss": "https://review-k.staging.account.gov.uk",
"exp": 1739024688,
"vc": {
"type": [
"VerifiableCredential",
"IdentityCheckCredential"
],
"credentialSubject": {
"name": [
{
"nameParts": [
{
"type": "GivenName",
"value": "KENNETH"
},
{
"type": "FamilyName",
"value": "DECERQUEIRA"
}
]
}
],
"address": [
{
"streetName": "HADLEY ROAD",
"postalCode": "BA2 5AA",
"buildingNumber": "8",
"addressLocality": "BATH",
"validFrom": "2021-01-01"
}
],
"birthDate": [
{
"value": "1965-07-08"
}
]
},
"evidence": [
{
"txn": "9LTRGXFJZZ",
"verificationScore": 2, …
```
> OJ-2652: Add @context to Experian KBV Vc

- build.gradle
- lambdas/issuecredential/build.gradle
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/VerifiableCredentialConstants.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandlerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialServiceTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/fixtures/TestFixtures.java
When included in the VCs, the public key id (kid) allows verifiers to determine which key a VC was signed with. Having all the issuers publish the correct information in the JWT header will result in standardisation across the programme.
see https://govukverify.atlassian.net/browse/OJ-2720
> OJ-2720: implement kid

- build.gradle
Bumped cri lib
The kid in the JWT header was formatted wrong. Changes to cri lib now remove https:// from the issuer and formats the kid with a hash like `did:web:Issuer#HashedKeyID` instead of with a colon like `did:web:Issuer:HashedKeyID`
- [OJ-2720](https://govukverify.atlassian.net/browse/OJ-2720)
[OJ-2720]: https://govukverify.atlassian.net/browse/OJ-2720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-272: Bump cri-lib to fix kid format

- .github/workflows/post-merge-deploy-to-dev.yml
- .github/workflows/post-merge-package-for-build.yml
Tested using dev platform upload action in dev workflow ahead of applying it to the build workflow
Post test added change for build as well
The rusty-action action is is no longer maintained and the dev platform have an action that handles the same functionality.
- [IPS-503](https://govukverify.atlassian.net/browse/IPS-503)
- Pacts are failing in the dev workflow but this PR does not make any changes to cause this issue
[IPS-503]: https://govukverify.atlassian.net/browse/IPS-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> replace rusty-actions with dev-platform upload-action

- .cfnlintrc
- integration-tests/src/test/java/gov/uk/kbv/api/stepdefinitions/KbvSteps.java
Added /kid assertion for JWT headers
/kid have been added to the JWT headers
- [OJ-2720](https://govukverify.atlassian.net/browse/OJ-2720)
[OJ-2720]: https://govukverify.atlassian.net/browse/OJ-2720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2720: Update integration test to include kid in JWT assertion

- integration-tests/src/test/resources/cucumber.properties
Remove cucumber publish quiet
It's been deprecated as per the [docs](https://github.com/cucumber/cucumber-js/blob/main/docs/deprecations.md)
> BAU: Remove cucumber publish quiet

- .cfnlintrc
- infrastructure/lambda/template.yaml
```
Check Fn::If has a path that cannot be reached] (['Fn::If', 1] is not reachable. 
When setting condition 'IsDevEnvironment' to True. Where existing status for condition 'IsNotDevEnvironment' is True)
```
The basically saying the condition `IsDevEnvironment` is never used because of the condition `IsNotDevEnvironment` applied when the resource is defined therefore the IsDevEnvironment can be removed entirely.
Also removed `Dimensions: []` as flagged by linter
Remove `.cfnlintrc` this was temporary way to ignore the linting issues. due to upgrade of SAM CLI to version 1.123.0 
in the github Action
**NB**:
See: https://govukverify.atlassian.net/browse/OJ-2255 which is a related ticket, that's outside the scope of this one.
The `DEV` stack for KBV and ADDRESS are actually more like the …
> OJ-2778: Resolving linting issue

- build.gradle
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGateway.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/MetricsService.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGatewayTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/MetricsServiceTest.java
Added two new metrics for "getQuestion" and "submitQuestion" API to check latency.
The original method `sendResultMetric` did not have the correct unit of measurement (ms) for the metric, so we were not able create the appropriate Dynatrace dashboards or see the duration time properly on the Cloudwatch metric graph.
To increase observability.
- [OJ-2731](https://govukverify.atlassian.net/browse/OJ-2731)
[OJ-2731]: https://govukverify.atlassian.net/browse/OJ-2731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2731: Adding new metric for latency

- integration-tests/src/test/java/gov/uk/kbv/api/client/KbvApiClient.java
- integration-tests/src/test/java/gov/uk/kbv/api/stepdefinitions/KbvSteps.java
- integration-tests/src/test/java/gov/uk/kbv/api/util/AnswerResource.java
- integration-tests/src/test/resources/HildaHead.json
- integration-tests/src/test/resources/features/KbvApiAbandonPath.feature
- integration-tests/src/test/resources/features/KbvApiHappyPath.feature
- integration-tests/src/test/resources/features/KbvApiUnhappyPath.feature
see: https://govukverify.atlassian.net/browse/OJ-2689
AnswerResource extended to handle multiple users, use the row number of in the spreadsheet to select which the user on which the features are run
support 3 new questions
> OJ-2689: Enable three new questions

- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/exception/InvalidSoapTokenException.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/security/Base64TokenCacheLoader.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/security/Base64TokenEncoder.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/security/Base64TokenEncoderTest.java
Experian WASP service errored on https://github.com/govuk-one-login/ipv-cri-kbv-api/blob/main/lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/security/Base64TokenEncoder.java#L20
If the token contains an error we can log what the token is
- [INCIDEN-937](https://govukverify.atlassian.net/browse/INCIDEN-937)
[INCIDEN-937]: https://govukverify.atlassian.net/browse/INCIDEN-937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> INCIDEN-937: Add logging to Base64TokenEncoder

- infrastructure/lambda/template.yaml
- Added `UseCanaryDeploymentAlarms` condition
Only if the if the strategy is not `AllAtOnce` should:
- Canary alarms be used to roll back deployments
- Canary alarms be deployed 
- [IPS-1155](https://govukverify.atlassian.net/browse/IPS-1155)
[IPS-1155]: https://govukverify.atlassian.net/browse/IPS-1155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1155: Refine alarms

- lambdas/abandon/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/AbandonKbvHandlerTest.java
Code issue - Remove this unused "result" local variable
Updated the sendAuditEvent in the abandon unit test to include the event name rather than anyString and asserted on the result variable status code.
The following issues were highlighted in Sonarcloud which helps us identify areas of code that have issues that may make it hard to maintain:
Issue 1: Code issue - Remove this unused "result" local variable.
[OJ-785](https://govukverify.atlassian.net/browse/OJ-785)
[OJ-785]: https://govukverify.atlassian.net/browse/OJ-785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-785: Fix sonar cloud code smells in abandon handler test

- infrastructure/lambda/template.yaml
- Set alarm actions to true
- This step should be done after the initial alarm deployment to avoid spamming the slack channels
- [IPS-1155](https://govukverify.atlassian.net/browse/IPS-1155)
[IPS-1155]: https://govukverify.atlassian.net/browse/IPS-1155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1155: Set alarms to true

- integration-tests/src/test/java/gov/uk/kbv/api/stepdefinitions/KbvSteps.java
- integration-tests/src/test/java/gov/uk/kbv/api/util/AnswerResource.java
- integration-tests/src/test/resources/CarolineCoulson.json
- integration-tests/src/test/resources/features/KbvApiHappyPath.feature
- lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
- lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java
- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
- lambdas/question/src/test/java/uk.gov.di.ipv.cri.kbv.api.handler/QuestionHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/KbvAlert.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/KbvResponsesAuditExtension.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/KbvResult.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionsResponse.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/QuestionsResponseMapper.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/domain/KbvResponsesAuditExtensionTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/domain/QuestionsResponseTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/gateway/QuestionsResponseMapperTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/util/TestDataCreator.java
If a user has passed the attempt threshold, upon trying again an Alert will be included in the SAA response along with the question. We want to include when an alert is present in the RESPONSE_RECEIVED audit event.
- Added KBVAlert to mapped response from Experian to handle alerts being included in the results.
- Refactored audit extension code to also include repeatAttemptAlert in the `experianIiqResponse` block for RESPONSE_RECEIVED audit events.
- Added units tests for scenarios.
- Added integration test for SAA repeatAttemptAlert.
So that whenever a user is trying to access experian kbv more than the allowed attempts we can monitor and investigate potential fraud attempts in real-time.
The alert message for screenless clients will be sent along with the questions, except where …
> OJ-2771: Add repeatAttemptAlert to Response Received Audit Event

- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KeyStoreLoader.java
Fixes [java:S5443](https://sonarcloud.io/organizations/govuk-one-login/rules?open=java%3AS5443&rule_key=java%3AS5443) 
Sonar does a hard check for directories like /tmp and it does not consider the AWS Lambda environment as part of its check. Since tmp is the only usable space we have, this PR add a comment to ignore the Sonar warning. 
There are occurrences of this being done in other repos: https://github.com/search?q=org%3Agovuk-one-login+%2F%2F+NOSONAR&type=code
- [OJ-2829](https://govukverify.atlassian.net/browse/OJ-2829)
[OJ-2829]: https://govukverify.atlassian.net/browse/OJ-2829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add "NOSONAR"

- infrastructure/lambda/private-api.yaml
- infrastructure/lambda/public-api.yaml
- infrastructure/lambda/template.yaml
- Point apispec to live alias of the lambdas
- Edit the lambda permissions to allow apigw to invoke the live alias
- Update resource names for alarms
- Ensure apigw has permissions to invoke live alias of lambdas
- [IPS-1087](https://govukverify.atlassian.net/browse/IPS-1087)
[IPS-1097]: https://govukverify.atlassian.net/browse/IPS-1097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-1087]: https://govukverify.atlassian.net/browse/IPS-1087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1087: Update lambda canaries

- infrastructure/lambda/private-api.yaml
- infrastructure/lambda/public-api.yaml
- infrastructure/lambda/template.yaml
Reverts the following changes:
> ### What changed
> 
> - Point apispec to live alias of the lambdas
> - Edit the lambda permissions to allow apigw to invoke the live alias
> - Update resource names for alarms
> 
> ### Why did it change
> 
> - Ensure apigw has permissions to invoke live alias of lambdas
> 
> ### Issue tracking
> 
> 
> 
> 
> - [IPS-1087](https://govukverify.atlassian.net/browse/IPS-1087)
[IPS-1087]: https://govukverify.atlassian.net/browse/IPS-1087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert "IPS-1087: Update lambda canaries"

- infrastructure/lambda/template.yaml
- Increase EvaluationPeriods
- Add permissions for apigw to invoke the live lambda
- Avoid false positives
- Permissions needed for 2 versions of the lambdas
- [IPS-1213](https://govukverify.atlassian.net/browse/IPS-1213)
[IPS-1213]: https://govukverify.atlassian.net/browse/IPS-1213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1213: Lambda canaries

- infrastructure/lambda/template.yaml
Reverts govuk-one-login/ipv-cri-kbv-api#422
- This was the fix to add extra permissions for APIGW to invoke the lambda alias
- However, the traffic tests still failed
- This PR (as well as https://github.com/govuk-one-login/ipv-cri-kbv-api/pull/423) will be reverted for now to unblock the pipeline
> Revert "IPS-1213: Lambda canaries"

- infrastructure/lambda/private-api.yaml
- infrastructure/lambda/public-api.yaml
- infrastructure/lambda/template.yaml
Reverts govuk-one-login/ipv-cri-kbv-api#423
- Revert lambda alias changes
- https://github.com/govuk-one-login/ipv-cri-kbv-api/pull/422 failed traffic tests so both these PRs are being reverted to unblock the pipeline
- See https://gds.slack.com/archives/C04RH15THAL/p1730721625257609 for context
> Revert "Revert "Revert "IPS-1087: Update lambda canaries"""

- infrastructure/lambda/template.yaml
Renamed alarms to include Experian.
We now have multiple KBV CRIs and have introduced a naming convention of {third party service} KBV to reduce confusion across the programme. This means that KBV needs to be renamed to Experian KBV
- [OJ-2795](https://govukverify.atlassian.net/browse/OJ-2795)
[OJ-2795]: https://govukverify.atlassian.net/browse/OJ-2795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2795: Rename Alarms with Experian

- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/security/SoapToken.java
Collecting latency for the soap token call. This PR creates a new metric called `get_soap_token_duration` so that we can understand how we can make our system more performant.
- [OJ-2840](https://govukverify.atlassian.net/browse/OJ-2840)
[OJ-2840]: https://govukverify.atlassian.net/browse/OJ-2840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2840: Collect SOAP token latency as a metric

- .github/workflows/check-pr.yml
- .github/workflows/clean-up-deployments.yml
- .github/workflows/code-quality.yml
- .github/workflows/delete-deployment.yml
- .github/workflows/deploy-branch.yml
- .github/workflows/package-for-build.yml
- .github/workflows/package-for-dev.yml
- .github/workflows/run-integration-tests.yml
- .github/workflows/scan-repo.yml
- README.md
- deploy.sh
- infrastructure/lambda/private-api.yaml
- infrastructure/lambda/public-api.yaml
- infrastructure/lambda/samconfig.toml
- infrastructure/lambda/template.yaml
- integration-tests/src/test/resources/features/KbvApiAbandonPath.feature
- integration-tests/src/test/resources/features/KbvApiHappyPath.feature
- integration-tests/src/test/resources/features/KbvApiUnhappyPath.feature
**OJ-2255: Add localdev environment to the template**
- Delete `DevOnlyKBVApi` and use the private API in dev instead
- Set the endpoint configuration and access based on the `localdev` variable
- Add mappings for the `localdev` environment (mirrors `dev`)
- Update the deploy script to use the `localdev` environment
- Add a `samconfig.toml` file with the correct config for `localdev`
- Update the Preview workflow to use the `localdev` environment
- Update integration tests to run with the localdev env
Remove the `pre_merge` prefix from integration test tags since they are all "pre-merge" and adding the same qualifier to each test doesn't help to differentiate between them.
**OJ-2255: Update APIs**
- Update the API config to match other templates
- Use references to the log groups and …
> OJ-2255: Add localdev environment to the template

- build.gradle
Update to latest common-library version
To deprecate SQS implementation and ensure CRIs are using the latest common-library version
- [OJ-2740](https://govukverify.atlassian.net/browse/OJ-2740)
[OJ-2740]: https://govukverify.atlassian.net/browse/OJ-2740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2740: Update to latest cri-lib version

- integration-tests/src/test/resources/features/schema/IPV_KBV_CRI_START.json
The evidence block has been changed to an array. This change was not reflected in KBV and the tests started failing once common lambdas was updated. 
The reason this was not captured before is because of how common lambdas is deployed. The last deployment of common-lambdas happened in 1st August 2024 - which did not contain the change to the START event. 
The next deployment happened on the 16th December 2024 which contained the array change.
> tests: update IPV_KBV_CRI_START schema to accept an array for the evidence block

- infrastructure/lambda/template.yaml
- Add additional Alias perms in separate PR
- Cloudwatch does not update resources in a particular order
- Merging this PR before any API changes ensures that the additional permissions are in place before updating the spec
- [IPS-1213](https://govukverify.atlassian.net/browse/IPS-1213)
[IPS-1213]: https://govukverify.atlassian.net/browse/IPS-1213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1213: Add permissions only

- infrastructure/lambda/private-api.yaml
- infrastructure/lambda/public-api.yaml
- infrastructure/lambda/template.yaml
- Point apispec to live alias of the lambdas
- Update resource names for alarms
- (The lambda alias permissions were merged first in this PR: https://github.com/govuk-one-login/ipv-cri-kbv-api/pull/429)
- To allow APIGW to invoke the alias of the lambda
- [IPS-1213](https://govukverify.atlassian.net/browse/IPS-1213)
[IPS-1213]: https://govukverify.atlassian.net/browse/IPS-1213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1213: Update API spec to point to lambda alias

- lib/build.gradle
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/security/HeaderHandler.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/security/SoapTokenRetriever.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/ServiceFactory.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/util/SoapTokenUtils.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/security/HeaderHandlerTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/security/SoapTokenRetrieverTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/util/SoapTokenUtilsTest.java
Added an exponential retry logic for when the token is returned back to us by Experian as "error".
The retry logic works as follows:
1. Attempt to get a token
2. If the token is error sleep for 500ms * the current iteration
3. If after 3 retries the a valid token is not returned: return whatever Experian has provided
The threshold for expired tokens is 2 hours. 
To mitigate against errors that can be solved by re-trying authentication with Experian.
- [OJ-2841](https://govukverify.atlassian.net/browse/OJ-2841)
[OJ-2841]: https://govukverify.atlassian.net/browse/OJ-2841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2841: SOAP token

- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/security/HeaderHandler.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/security/SoapTokenRetriever.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/util/SoapTokenUtils.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/security/HeaderHandlerTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/security/SoapTokenRetrieverTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/util/SoapTokenUtilsTest.java
Added caching to the SOAP token.
A token is considered invalid if it's expiry is passed our threshold (2 hours).
If the token expiry is over our threshold, when calling getSoapToken() we will fetch a new token.
If the token is over our expiry and we fail to get a new token from experian, we will use the valid (but past our threshold) cached token. 
If both experian and our cache is invalid then we will return the token received and let the existing error handling continue. 
So that we do not always making a call to Experian. If the LoginWithCertificate breaks, we can still fall back to our cached valid token. 
- [OJ-2908](https://govukverify.atlassian.net/browse/OJ-2908)
[OJ-2908]: https://govukverify.atlassian.net/browse/OJ-2908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
> OJ-2908: SOAP token cache

- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/IdentityIQWrapper.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGateway.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGatewayFactory.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/security/HeaderHandler.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/security/SoapTokenRetriever.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/ServiceFactory.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/util/SoapTokenUtils.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/gateway/IdentityIQWrapperTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGatewayFactoryTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGatewayTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/security/HeaderHandlerTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/security/SoapTokenRetrieverTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/security/SoapTokenTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/ServiceFactoryTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/util/SoapTokenUtilsTest.java
In the event of a long running session the SOAP Token can expiry, this PR aims to refresh the token
mid-flow when the question /answer lambda has not had a chance to restart. 
The refresh cycle is currently based on `isTokenValidWithinThreshold ` any token outside the 2-hour window will be subject to being refreshed. 
In the unlikely event that getting a fresh token after the 2-hours is not possible, the last valid cache token will be used. This means a chatty API, an alternative could have been to conduct the refresh based on an offset on the expiry maybe 30mins or an hour before expiry, given that token life time is about 9 hours. This is a trade-off that has been made.
The IdentityIQWrapper class, wraps IdentityIQWebServiceSoap class
It will manage the token refresh on expiry of a long …
> OJ-2842: token retry during journey

- lib/build.gradle
- Update version from `1.2` to `2.0.1` for `com.github.bjornvester.wsdl2java` plugin
- Added `useJakarta` to `false` within the wsdl configuration to prevent imports for SoapToken, KBVClientFactory, HeaderHandler and HeaderHandlerResolver being changed and moved to use `import jakarta.xml.ws.*` which causes the following error for the ServiceFactoryTest > testGetKbvGatewayReturnsExceptionWhenCreationFails() :
Unexpected exception type thrown, expected: <uk.gov.di.ipv.cri.kbv.api.exception.KBVGatewayCreationException> but was: <jakarta.xml.ws.WebServiceException>
Expected :class uk.gov.di.ipv.cri.kbv.api.exception.KBVGatewayCreationException
Actual   :class jakarta.xml.ws.WebServiceException
The Old Experian Stub used version 1.2.0 of the WSDL2JAVA, this was updated to version 2.0.1 …
> OJ-2889: fix - update wsdl2java version from 1.2 to 2.0.1

- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGateway.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/security/SoapToken.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/MetricsService.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/ServiceFactory.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGatewayTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/security/SoapTokenTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/MetricsServiceTest.java
Added `sendDurationMetric` method to MetricsService to be used by handlers after sending a request to Experian.
Removed;
- Duplicate duration calculation logic
- Removed execution_duration dimension from Result metric as duration is a metric not a dimension.
- Removed transition_id dimension from Result metric as it's no longer needed.
I have kept the duration metric names the same to keep easily viewable with historic data.
De-duplicate latency metric code, 
- [OJ-2845](https://govukverify.atlassian.net/browse/OJ-2845)
[OJ-2845]: https://govukverify.atlassian.net/browse/OJ-2845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2845: Refactor experian request duration metric

- build.gradle
spotlessApply is automatically run when build is invoked.
When developing locally, `gradle build` will fail when you forget to run spotless. This means a developer has to manually run spotless first and then build which can cause an inconvenience. 
By automatically running spotless, developers do not need to worry about running spotless themselves. 
The code-quality GHA will still flag spotless issues if it has not been applied before committing.
> feat: run spotlessApply before build is run

- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandler.java
SQSClient is being referenced from the ServiceFactory instead of manually creating it.
To support SnapStart, we have to handle credentials differently. The ServiceFactory is a wrapper over ConfigurationService which is provided from ipv-cri-lib. The ConfigurationService gives us a SnapStart suitable reference of the SQSClient that we can use. 
- [OJ-3065](https://govukverify.atlassian.net/browse/OJ-3065)
[OJ-3065]: https://govukverify.atlassian.net/browse/OJ-3065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: update IssueCredentialHandler to use the SQSClient provided by the ServiceFactory

- lambdas/issuecredential/build.gradle
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialService.java
- lib/build.gradle
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/ServiceFactory.java
KMSClient is being referenced from the ServiceFactory instead of manually creating it.
To support SnapStart, we have to handle credentials differently. The ServiceFactory is a wrapper over ConfigurationService which is provided from ipv-cri-lib. The ConfigurationService gives us a SnapStart suitable reference of the KMSClient that we can use.
- [OJ-3064](https://govukverify.atlassian.net/browse/OJ-3064)
[OJ-3064]: https://govukverify.atlassian.net/browse/OJ-3064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: use kms client from ServiceFactory in VerifiableCredentialService

- lambdas/abandon/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/AbandonKbvHandler.java
- lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandler.java
- lambdas/question/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionHandler.java
- lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/KBVStorageService.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/KBVStorageServiceTest.java
The `KBVStorageService` now receives `configurationService` and `dynamodbClient` from cri-lib of`ClientProviderFactory`
There was no test for `KBVStorageService` so test have also been added
As part of SnapStart, AWS credentials are loaded differently and thus changes need to be made. 
- [OJ-3063](https://govukverify.atlassian.net/browse/OJ-3063)
[OJ-3063]: https://govukverify.atlassian.net/browse/OJ-3063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3063: Update to use clientProviderFactory dynamodbClient

- infrastructure/lambda/template.yaml
Added SnapStart to the Lambdas
To improve cold start performance of the CRI.
- [OJ-3061](https://govukverify.atlassian.net/browse/OJ-3061)
[OJ-3061]: https://govukverify.atlassian.net/browse/OJ-3061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: enable SnapStart

- infrastructure/lambda/template.yaml
SnapStart enabled in production.
Performance test has been run comparing before and after. We have verified that adding SnapStart has increased our performance so we are happy to roll this to production.
- [OJ-3062](https://govukverify.atlassian.net/browse/OJ-3062)
[OJ-3062]: https://govukverify.atlassian.net/browse/OJ-3062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: apply snapstart in production

- .github/workflows/deploy-branch.yml
- infrastructure/lambda/template.yaml
Unpin sam version from preview stack. 
Reverts https://github.com/govuk-one-login/ipv-cri-kbv-api/pull/452 but keeps the newer version of the action.
Set`PermissionsBoundary` default value to `""` instead of `"none"`.  For some reason cfn-lint was flagging an E3033 linting error if there was a value, possibly something to do with the transforms.
No longer requires pinning as the linting bug was fixed in Sam CLI 1.135.0 which ubuntu-latest image now uses.
Fix `E3033 'none' is shorter than 20` being flagged on `PermissionsBoundary` default value. 
- [OJ-3049](https://govukverify.atlassian.net/browse/OJ-3049)
[OJ-3049]: https://govukverify.atlassian.net/browse/OJ-3049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3049: Unpin sam-version from preview action

- infrastructure/lambda/template.yaml
Add new SessionLambdaFailedToVerifyJWTAlarm and TokenLambdaFailedToVerifyJWTAlarm alarms
So that we are quickly alerted when there is an issue verifying the JWTs that core is sending address CRI.
The new metric has been added in common lambdas https://github.com/govuk-one-login/ipv-cri-common-lambdas/pull/473
- [OJ-3080](https://govukverify.atlassian.net/browse/OJ-3080)
[OJ-3080]: https://govukverify.atlassian.net/browse/OJ-3080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3080: Add alarms for jwt_verification_failed

- .github/workflows/run-integration-tests.yml
- README.md
We've stopped using the backend api(s) of the web [core-stub](https://cri.core.stubs.account.gov.uk/)
Integration tests now runs on headless core stub
> chore: Update README.md and integration-tests .git-action 

- infrastructure/lambda/template.yaml
Add slack alerts to all alarms.
So that we have visibility of our Alarms changing state, we want to ensure all of our alarms are configured to post to our Slack channels when they change state. 
This can help us catch issues faster if there are issues with new changes.
- [OJ-3188](https://govukverify.atlassian.net/browse/OJ-3188)
[OJ-3188]: https://govukverify.atlassian.net/browse/OJ-3188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3188: Add slack alerts to all alarms

- .github/workflows/code-quality.yml
- .github/workflows/deploy-branch.yml
- .github/workflows/package-for-build.yml
- .github/workflows/package-for-dev.yml
- .github/workflows/run-pact-tests.yml
- .github/workflows/run-unit-tests.yml
- .sdkmanrc
- build.gradle
- infrastructure/lambda/template.yaml
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/kbv/api/service/EvidenceFactory.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/IssueCredentialHandlerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/util/PreLambdaHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/VerifiableCredentialServiceTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/gateway/KeyStoreLoaderTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/kbv/api/service/ServiceFactoryTest.java
* Workflows use Java 21
* CloudFormation template updated to use Java 21
* Tests updated to match Java upgrade
**Note**: `JavaVersion.VERSION_17` in the compatibility section because `_21` isn't recognised and I cannot flat out remove this section because the tests require it set. No big deal at the moment. 
These changes have been applied so that we can support Java 21. As per team manual, we should be using the latest LTS version. 
- [OJ-3085](https://govukverify.atlassian.net/browse/OJ-3157)
[OJ-3085]: https://govukverify.atlassian.net/browse/OJ-3085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3085: upgrade to Java 21

- infrastructure/lambda/template.yaml
- Change SupportManualURL to mapping
- Add deploy alarms condition
Because params cannot easily be updated
Before
After
- [OJ-3214](https://govukverify.atlassian.net/browse/OJ-3214)
[OJ-3214]: https://govukverify.atlassian.net/browse/OJ-3214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3214: Change SupportManualURL to mapping

- infrastructure/lambda/template.yaml
turn alarm on but remove pagerduty action
So that we are notified about failures, but they can be investigated in hours while we are still seeing false positives
- [OJ-3243](https://govukverify.atlassian.net/browse/OJ-3243)
[OJ-3243]: https://govukverify.atlassian.net/browse/OJ-3243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3243: turn alarm on but remove pagerduty action

- integration-tests/src/test/java/gov/uk/kbv/api/stepdefinitions/HealthCheckEndpointStepDefinition.java
- integration-tests/src/test/resources/features/HealthCheckEndpoint.feature
Added tests for the `/healthcheck/thirdparty` endpoint to assert that it is not accessible outside the VPN.
These tests do not cover functionality of the endpoint i.e. the data returned, that responsibility is left to the unit tests. Additionally, it'll be a challenge to expose the endpoint for localdev. 
- [OJ-3168](https://govukverify.atlassian.net/browse/OJ-3168)
[OJ-3168]: https://govukverify.atlassian.net/browse/OJ-3168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test: create integration test for /healthcheck/thirdparty

- infrastructure/lambda/template.yaml
Added **Experian** into the description of the JsonWebKeys alarms so it is more obvious to support which service is alarming. Also adjusted
- **apiName** to point to the current name of the Experian public KBV api
Make alarms more obvious and consistent
- [OJ-3179](https://govukverify.atlassian.net/browse/OJ-3179)
- https://github.com/govuk-one-login/team-manual/pull/967
[OJ-3179]: https://govukverify.atlassian.net/browse/OJ-3179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3179: Make alarms clearer by adding Experian

- lambdas/healthcheck/src/main/java/uk/gov/di/ipv/cri/kbv/healthcheck/handler/HealthCheckHandler.java
- lambdas/healthcheck/src/main/java/uk/gov/di/ipv/cri/kbv/healthcheck/handler/assertions/soap/Certificate.java
- lambdas/healthcheck/src/main/java/uk/gov/di/ipv/cri/kbv/healthcheck/handler/assertions/soap/CustomX509TrustManager.java
- lambdas/healthcheck/src/main/java/uk/gov/di/ipv/cri/kbv/healthcheck/handler/assertions/soap/SOAPRequestAssertion.java
- lambdas/healthcheck/src/test/java/uk/gov/di/ipv/cri/kbv/healthcheck/handler/HealthCheckHandlerTest.java
- lambdas/healthcheck/src/test/java/uk/gov/di/ipv/cri/kbv/healthcheck/handler/assertions/soap/CustomX509TrustManagerTest.java
Added a section to the report to show which certificates were checked against the system trust store. 
Experian changed their root CA to use Sectigo. This PR shows visibility on what certificates Experian uses so that we can confirm/verify our trust with Experians server. 
Note: These changes are not secret and show the subject/issuer of the publicly known CAs. 
**Added section to SOAPRequestAssertion**
```json
"trust_manager" : {
"server" : [ {
"subject" : "CN=*.execute-api.eu-west-2.amazonaws.com",
"issuer" : "CN=Amazon RSA 2048 M03,O=Amazon,C=US"
}, {
"subject" : "CN=Amazon RSA 2048 M03,O=Amazon,C=US",
"issuer" : "CN=Amazon Root CA 1,O=Amazon,C=US"
}, {
"subject" : "CN=Amazon Root CA 1,O=Amazon,C=US",
"issuer" : "CN=Starfield Services Root Certificate Authority - G2,O=Starfield …
```
> feat: show certificates checked in trust manager when calling SOAP API

- lambdas/healthcheck/src/main/java/uk/gov/di/ipv/cri/kbv/healthcheck/handler/assertions/FailReport.java
Add logging of exception for when a FailReport has been generated. 
To give us more visibility of what the error cause is when debugging. 
- [OJ-3168](https://govukverify.atlassian.net/browse/OJ-3168)
[OJ-3168]: https://govukverify.atlassian.net/browse/OJ-3168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add logging on exception when the FailReport is created

- lambdas/healthcheck/src/main/java/uk/gov/di/ipv/cri/kbv/healthcheck/handler/assertions/soap/Certificate.java
- lambdas/healthcheck/src/main/java/uk/gov/di/ipv/cri/kbv/healthcheck/handler/assertions/soap/CustomTrustManager.java
- lambdas/healthcheck/src/main/java/uk/gov/di/ipv/cri/kbv/healthcheck/handler/assertions/soap/SOAPRequestAssertion.java
- lambdas/healthcheck/src/test/java/uk/gov/di/ipv/cri/kbv/healthcheck/handler/assertions/soap/CustomTrustManagerTest.java
Fixed SOAP request not working in staging & prod. Re-added trust manager reporting as this was previously removed to debug (incase that was the reason SOAP request was not working). 
SOAP request was not working in staging/prod
- [OJ-3168](https://govukverify.atlassian.net/browse/OJ-3168)
[OJ-3168]: https://govukverify.atlassian.net/browse/OJ-3168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add trust manager entries to output & fix soap connection issue

- lambdas/healthcheck/src/main/java/uk/gov/di/ipv/cri/kbv/healthcheck/handler/HealthCheckHandler.java
- lambdas/healthcheck/src/main/java/uk/gov/di/ipv/cri/kbv/healthcheck/handler/assertions/ssl/SSLHandshakeAssertion.java
- lambdas/healthcheck/src/main/java/uk/gov/di/ipv/cri/kbv/healthcheck/handler/config/Configuration.java
SSL test was hard coded to use Experian prod. This has been updated to use the provided url in secrets manager. 
So that we can test UAT.
- [OJ-3168](https://govukverify.atlassian.net/browse/OJ-3168)
[OJ-3168]: https://govukverify.atlassian.net/browse/OJ-3168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3168: update SSL test to use correct host

- .pre-commit-config.yaml
- infrastructure/lambda/template.yaml
Changed the critical alarm to have to be 80% of invocations for 3 periods instead of just 1 error. This should only alarm if it is a much greater issue. 
Added a warning alarm so team can see if this is happening at a much lower level (10%).
Bumped pre-commit cfn-lint version
..LambdaFailedToVerifyJWTAlarm was firing to frequently for a critical (out of hours support) alarm.
- [OJ-3243](https://govukverify.atlassian.net/browse/OJ-3243)
[OJ-3243]: https://govukverify.atlassian.net/browse/OJ-3243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3243: Rename VerifyJWT alarms

- infrastructure/lambda/template.yaml
Added permissions to HealthCheckFunction to fetch SSM parameters
Healthcheck endpoint is giving a 500 because it does not have permissions to read from SSM
- [OJ-3265](https://govukverify.atlassian.net/browse/OJ-3265)
[OJ-3265]: https://govukverify.atlassian.net/browse/OJ-3265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add permissions to HealthCheckFunction to fetch SSM params

- infrastructure/lambda/template.yaml
- lambdas/healthcheck/src/main/java/uk/gov/di/ipv/cri/kbv/healthcheck/handler/config/Configuration.java
- lambdas/healthcheck/src/main/java/uk/gov/di/ipv/cri/kbv/healthcheck/handler/config/ExperianSecrets.java
Use the clientId when looking up SSM parameter
The ConfigurationService looks up parameters using a prefix so the previous logic was failing.
> fix: use clientId when looking up wasp url in HealthCheckFunction

- .github/workflows/deploy-branch.yml
- .github/workflows/package-for-build.yml
- .github/workflows/package-for-dev.yml
- .github/workflows/run-integration-tests.yml
- .github/workflows/run-pact-tests.yml
- .github/workflows/run-unit-tests.yml
- .github/workflows/scan-repo.yml
git-action underline gradle changed
`post-compile-weaving` broke due to that `git-action` has upgrading the gradle version. 
Therefore pinning git-action to **version 8.13**
see: https://github.com/govuk-one-login/ipv-cri-kbv-api/blob/main/.sdkmanrc#L4
This is the error that would be seen **without** this change https://github.com/govuk-one-login/ipv-cri-kbv-api/actions/runs/16882903369/job/47823067700?pr=531
> Fix: pin gradle version

- lambdas/healthcheck/src/main/java/uk/gov/di/ipv/cri/kbv/healthcheck/handler/assertions/soap/SOAPRequestAssertion.java
- lambdas/healthcheck/src/main/java/uk/gov/di/ipv/cri/kbv/healthcheck/handler/assertions/ssl/SSLHandshakeAssertion.java
- lambdas/healthcheck/src/main/java/uk/gov/di/ipv/cri/kbv/healthcheck/util/LatencyTracker.java
- lambdas/healthcheck/src/test/java/uk/gov/di/ipv/cri/kbv/healthcheck/util/LatencyTrackerTest.java
Added latency to SSL handshake and SOAP request tests.
So that we can see the performance of Experian.
- [OJ-3390](https://govukverify.atlassian.net/browse/OJ-3390)
[OJ-3390]: https://govukverify.atlassian.net/browse/OJ-3390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add latencyInMs to SOAP and SSL tests

- infrastructure/lambda/template.yaml
- step-functions/certificate-expiry.asl.json
- Made the step function invoke the Lambda directly rather than hitting the API Gateway
- The API Gateway has restrictive permissions to ensure that it can be only called on the GDS VPN - this rule is not enabled in localdev stacks so this issue was missed on the original release.
- Added the step function ARN to the outputs of the CloudFormation stack
- This enables us to invoke the step function during integration testing
- OJ-3294
> OJ-3294 - Certificate expiry SFN infra fixes

- infrastructure/lambda/template.yaml
Update Dynatrace Arn to version 1_313
There is a more update version of dynatrace, [previous PR ](https://github.com/govuk-one-login/ipv-cri-kbv-api/pull/542) should now enable upgrading to it 
- [OJ-3393](https://govukverify.atlassian.net/browse/OJ-3393)
[OJ-3393]: https://govukverify.atlassian.net/browse/OJ-3393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3393: Update Dynatrace Lambda layer to 1.313

- infrastructure/lambda/template.yaml
Remove schedule name
Resource name is too long for dependabot preview stacks
> BAU: Remove schedule name

- build.gradle
- gradle/libs.versions.toml
Exclude the following clients so it uses CRT:
* netty-nio-client
* url-connection-client
Add the AWS CRT client into build.gradle so that we are using the version compatible with the AWS BOM that is in this CRI. At the moment, we're using an older version which comes from cri-lib.
Bump BOM to 2.33.9 (latest). 
- [OJ-3432](https://govukverify.atlassian.net/browse/OJ-3432)
[OJ-3432]: https://govukverify.atlassian.net/browse/OJ-3432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3432: Update AWS deps and include CRT client

- gradle/libs.versions.toml
- Updated to `com.nimbusds:oauth2-oidc-sdk` and `com.nimbusds:nimbus-jose-jwt` to use the latest version based on the dependabot alert [here](https://github.com/govuk-one-login/ipv-cri-kbv-api/security/dependabot/28) 
- Updated the latest version number for `com.diffplug.spotless:spotless-plugin-gradle` for this [alert](https://github.com/govuk-one-login/ipv-cri-kbv-api/security/dependabot/24)
NB: Unable to update `au.com.dius.pact:provider` dependency as the vulnerability is still in the latest release [here](https://mvnrepository.com/artifact/au.com.dius.pact/provider). No latest version for `org.apache.cxf:cxf-rt-frontend-jaxws` dependency [here](https://mvnrepository.com/artifact/org.apache.cxf/cxf-rt-frontend-jaxws).
To resolve dependabot alerts.
- …
> OJ-3439: fix - upgrade dependencies to the latest version

- infrastructure/lambda/template.yaml
As part of transitioning FMS WAF rule enforcement from COUNT to BLOCK, Security have set up custom policies for us to apply to our resources in scope. In COUNT mode FMS merely logs the rule violations, in BLOCK mode violating requests are actively blocked. 
The tags to implement this should only apply (conditionally) to resources deployed to dev, build and staging accounts. The tags must not apply to int and prod (there is a follow-up ticket for this:
Apply tagging conditional to meet the above requirement
Part of transitioning FMS WAF rule enforcement
**Tags on ApiGateway**
- [OJ-3445](https://govukverify.atlassian.net/browse/OJ-3445)
[OJ-3445]: https://govukverify.atlassian.net/browse/OJ-3445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3445: Add FMS tags for custom WAF policy

- .github/workflows/deploy-branch.yml
- deploy.sh
- infrastructure/lambda/template.yaml
Add `ForceLambdaUpdate` CF param and env var that can be used to force sam deployed (localdev) stacks to deploy new lambda versions every time.
With moving to resolving SSM Params at deploy time and passing them directly into our Lambda functions as environment variables, when deploying using Sam (local or pre-merge GHA) sometimes the small changes (e.g. an env var) do not publish new Lambda versions. This can cause deployment issues.
- [OJ-3462](https://govukverify.atlassian.net/browse/OJ-3462)
[OJ-3462]: https://govukverify.atlassian.net/browse/OJ-3462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3462: Add param to force localdev lambdas to update every time

- .github/workflows/deploy-branch.yml
Minor fix to timestamp generated in GHA for https://github.com/govuk-one-login/ipv-cri-kbv-api/pull/565
Set timestamp correctly
- [OJ-3462](https://govukverify.atlassian.net/browse/OJ-3462)
[OJ-3462]: https://govukverify.atlassian.net/browse/OJ-3462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3462: Fix GHA to set timestamp properly
